// ★このファイルはスプレッドシート（AppScript.txt の exportToTypeScript）から自動生成される。手動編集は次回の出力で上書きされるので注意。
export default {
    title: "謎キャン2026 1日目(2026/3/14)",
    startHour: 10,
    endHour: 20,
    blockMargin: 5,
    stages: [
      {
        id: "hall1",
        name: "ホール1",
        group: "街ハック！本社11F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "hall2",
        name: "ホール2",
        group: "街ハック！本社11F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "2E",
        name: "応接室 2E",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "2F",
        name: "応接室 2F",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "2G",
        name: "応接室 2G",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room201",
        name: "201",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room202",
        name: "202",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room203",
        name: "203",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room204",
        name: "204",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room205",
        name: "205",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room206",
        name: "206",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room207",
        name: "207",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room209",
        name: "209",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room210",
        name: "210",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room211",
        name: "211",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room212",
        name: "212",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room213",
        name: "213",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room214",
        name: "214",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room215",
        name: "215",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room216",
        name: "216",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room217",
        name: "217",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room218",
        name: "218",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room219",
        name: "219",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room220",
        name: "220",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room221",
        name: "221",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room222",
        name: "222",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room223",
        name: "223",
        group: "街ハック！本社2F",
        allowMultiple: "",
        allowOverlap: "",
      },
    ],
    schedules: [
      {
        id: 1001,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1002,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1003,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "13:10",
        endTime: "14:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1004,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "14:10",
        endTime: "15:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1005,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1006,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "16:10",
        endTime: "17:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1007,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "17:10",
        endTime: "18:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1008,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "18:10",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1009,
        stageId: "room205",
        title: "セイカイ x セイセイ ２",
        artist: "WHYNU",
        startTime: "19:10",
        endTime: "20:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 101,
        stageId: "hall1",
        title: "SCRAPE",
        artist: "リデルタ",
        startTime: "10:10",
        endTime: "11:50",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 102,
        stageId: "hall1",
        title: "SCRAPE",
        artist: "リデルタ",
        startTime: "13:00",
        endTime: "14:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 103,
        stageId: "hall1",
        title: "SCRAPE",
        artist: "リデルタ",
        startTime: "15:30",
        endTime: "17:10",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 104,
        stageId: "hall1",
        title: "SCRAPE",
        artist: "リデルタ",
        startTime: "18:00",
        endTime: "19:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 1101,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "10:10",
        endTime: "11:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1102,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1103,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "13:20",
        endTime: "14:10",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1104,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "14:40",
        endTime: "15:30",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1105,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "16:00",
        endTime: "16:50",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1106,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "17:20",
        endTime: "18:10",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1107,
        stageId: "room206",
        title: "はちゃめちゃマナー！？名刺交換バトル",
        artist: "ハードナッツ",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1201,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "10:10",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1202,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "11:40",
        endTime: "13:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1203,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "13:30",
        endTime: "14:50",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1204,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "15:00",
        endTime: "16:20",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1205,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "16:30",
        endTime: "17:50",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1206,
        stageId: "room207",
        title: "オートメーション・オペレーション",
        artist: "作人",
        startTime: "18:00",
        endTime: "19:20",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1301,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "10:10",
        endTime: "10:50",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1302,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "11:05",
        endTime: "11:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1303,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "12:00",
        endTime: "12:40",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1304,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "12:55",
        endTime: "13:35",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1305,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "13:50",
        endTime: "14:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1306,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "14:45",
        endTime: "15:25",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1307,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "15:40",
        endTime: "16:20",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1308,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "16:35",
        endTime: "17:15",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1309,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1310,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "18:25",
        endTime: "19:05",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1311,
        stageId: "room209",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "19:20",
        endTime: "20:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1401,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "10:10",
        endTime: "11:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1402,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "11:10",
        endTime: "12:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1403,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "12:10",
        endTime: "13:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1404,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "13:10",
        endTime: "14:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1405,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "14:10",
        endTime: "15:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1406,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1407,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "16:10",
        endTime: "17:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1408,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "17:10",
        endTime: "18:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1409,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "18:10",
        endTime: "19:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1410,
        stageId: "room210",
        title: "The Tower",
        artist: "rpurb",
        startTime: "19:10",
        endTime: "20:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 1501,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "10:10",
        endTime: "10:55",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1502,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "11:05",
        endTime: "11:50",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1503,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1504,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "12:55",
        endTime: "13:40",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1505,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "13:50",
        endTime: "14:35",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1506,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "14:45",
        endTime: "15:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1507,
        stageId: "room211",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "15:40",
        endTime: "16:25",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1601,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "10:10",
        endTime: "11:10",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1602,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "11:40",
        endTime: "12:40",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1603,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "13:10",
        endTime: "14:10",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1604,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1605,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "16:10",
        endTime: "17:10",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1606,
        stageId: "room212",
        title: "REALIDDLE",
        artist: "九大謎解き企画Quest",
        startTime: "17:40",
        endTime: "18:40",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1701,
        stageId: "room213",
        title: "INCIDENT",
        artist: "C-lock-row",
        startTime: "10:10",
        endTime: "11:40",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1702,
        stageId: "room213",
        title: "INCIDENT",
        artist: "C-lock-row",
        startTime: "12:05",
        endTime: "13:35",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1703,
        stageId: "room213",
        title: "INCIDENT",
        artist: "C-lock-row",
        startTime: "14:00",
        endTime: "15:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1704,
        stageId: "room213",
        title: "INCIDENT",
        artist: "C-lock-row",
        startTime: "15:55",
        endTime: "17:25",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1705,
        stageId: "room213",
        title: "INCIDENT",
        artist: "C-lock-row",
        startTime: "17:50",
        endTime: "19:20",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1801,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "10:10",
        endTime: "10:50",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1802,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "11:00",
        endTime: "11:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1803,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "11:50",
        endTime: "12:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1804,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "13:00",
        endTime: "13:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1805,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "13:50",
        endTime: "14:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1806,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "14:40",
        endTime: "15:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1807,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "15:40",
        endTime: "16:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1808,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1809,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "17:20",
        endTime: "18:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1810,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "18:20",
        endTime: "19:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1811,
        stageId: "room214",
        title: "IN THE FRAME",
        artist: "HEMMPL",
        startTime: "19:10",
        endTime: "19:50",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1901,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1902,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "11:40",
        endTime: "12:30",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1903,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "12:50",
        endTime: "13:40",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1904,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1905,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1906,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "16:20",
        endTime: "17:10",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1907,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1908,
        stageId: "room215",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2001,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "10:10",
        endTime: "10:55",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2002,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "11:20",
        endTime: "12:05",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2003,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "12:25",
        endTime: "13:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2004,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "13:40",
        endTime: "14:25",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2005,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "14:45",
        endTime: "15:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2006,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "15:50",
        endTime: "16:35",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2007,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "17:05",
        endTime: "17:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2008,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "18:10",
        endTime: "18:55",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2009,
        stageId: "room216",
        title: "moonitor",
        artist: "ツキノワ",
        startTime: "19:15",
        endTime: "20:00",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 201,
        stageId: "hall2",
        title: "宝石奪取計画月影の包囲網からの脱出",
        artist: "return 0;",
        startTime: "10:10",
        endTime: "11:50",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 202,
        stageId: "hall2",
        title: "宝石奪取計画月影の包囲網からの脱出",
        artist: "return 0;",
        startTime: "13:00",
        endTime: "14:40",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 203,
        stageId: "hall2",
        title: "宝石奪取計画月影の包囲網からの脱出",
        artist: "return 0;",
        startTime: "15:30",
        endTime: "17:10",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 204,
        stageId: "hall2",
        title: "宝石奪取計画月影の包囲網からの脱出",
        artist: "return 0;",
        startTime: "18:00",
        endTime: "19:40",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2101,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "10:10",
        endTime: "11:05",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2102,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "11:25",
        endTime: "12:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2103,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "12:40",
        endTime: "13:35",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2104,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "13:55",
        endTime: "14:50",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2105,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "15:10",
        endTime: "16:05",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2106,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "16:25",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2107,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "17:40",
        endTime: "18:35",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2108,
        stageId: "room217",
        title: "完治目論む白銀の歯科医院からの脱出",
        artist: "Unorthodox",
        startTime: "18:55",
        endTime: "19:50",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 2201,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "10:15",
        endTime: "11:00",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2202,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "11:15",
        endTime: "12:00",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2203,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "12:15",
        endTime: "13:00",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2204,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "13:15",
        endTime: "14:00",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2205,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "14:45",
        endTime: "15:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2206,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "15:45",
        endTime: "16:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2207,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "16:45",
        endTime: "17:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2208,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "17:45",
        endTime: "18:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2209,
        stageId: "room218",
        title: "wow国のwow様と遊ぼう！",
        artist: "snow glow",
        startTime: "18:45",
        endTime: "19:30",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 2301,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "10:20",
        endTime: "11:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2302,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "12:00",
        endTime: "12:50",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2303,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "13:20",
        endTime: "14:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2304,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "14:40",
        endTime: "15:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2305,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "16:20",
        endTime: "17:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2306,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "17:40",
        endTime: "18:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2307,
        stageId: "room219",
        title: "閉ざされし狼獄からの生還",
        artist: "あかずきん",
        startTime: "19:00",
        endTime: "19:50",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 2401,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "10:10",
        endTime: "11:10",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2402,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "11:20",
        endTime: "12:20",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2403,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "13:10",
        endTime: "14:10",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2404,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "14:20",
        endTime: "15:20",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2405,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "15:30",
        endTime: "16:30",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2406,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "16:40",
        endTime: "17:40",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2407,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "17:50",
        endTime: "18:50",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2408,
        stageId: "room220",
        title: "身代わりだらけの調剤実習からの帰還",
        artist: "白金謎解きラボ",
        startTime: "19:00",
        endTime: "20:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 2501,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "10:10",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2502,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "11:50",
        endTime: "13:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2503,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "14:00",
        endTime: "15:10",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2504,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "15:40",
        endTime: "16:50",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2505,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "17:15",
        endTime: "18:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2506,
        stageId: "room221",
        title: "カンダのエクセレントえっくす教室",
        artist: "Kanda",
        startTime: "18:50",
        endTime: "20:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2601,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "10:10",
        endTime: "11:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2602,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "11:15",
        endTime: "12:15",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2603,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "12:20",
        endTime: "13:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2604,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "13:25",
        endTime: "14:25",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2605,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "14:30",
        endTime: "15:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2606,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "15:35",
        endTime: "16:35",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2607,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "16:40",
        endTime: "17:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2608,
        stageId: "room222",
        title: "The BOX",
        artist: "melt",
        startTime: "17:45",
        endTime: "18:45",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2701,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "10:10",
        endTime: "11:20",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2702,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "11:40",
        endTime: "12:50",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2703,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "13:20",
        endTime: "14:30",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2704,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "14:50",
        endTime: "16:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2705,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "16:20",
        endTime: "17:30",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2706,
        stageId: "room223",
        title: "アットホームデリバリー",
        artist: "AnotherVision",
        startTime: "17:50",
        endTime: "19:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 301,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "10:10",
        endTime: "11:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 302,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "11:20",
        endTime: "12:15",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 303,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "12:30",
        endTime: "13:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 304,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "13:40",
        endTime: "14:35",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 305,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "14:50",
        endTime: "15:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 306,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "16:00",
        endTime: "16:55",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 307,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "17:10",
        endTime: "18:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 308,
        stageId: "2E",
        title: "不安定な異世界からの脱出",
        artist: "鹿児島大学謎解きサークルInTale",
        startTime: "18:20",
        endTime: "19:15",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 401,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "10:15",
        endTime: "11:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 402,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "11:30",
        endTime: "12:25",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 403,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "12:45",
        endTime: "13:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 404,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "14:00",
        endTime: "14:55",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 405,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "15:15",
        endTime: "16:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 406,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "16:30",
        endTime: "17:25",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 407,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "17:45",
        endTime: "18:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 408,
        stageId: "2F",
        title: "マッスルームからの脱出",
        artist: "仙台高専謎解き愛好会",
        startTime: "19:00",
        endTime: "19:55",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 501,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "10:10",
        endTime: "11:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 502,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "11:30",
        endTime: "12:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 503,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "13:30",
        endTime: "14:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 504,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "14:50",
        endTime: "15:50",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 505,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "16:10",
        endTime: "17:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 506,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "17:30",
        endTime: "18:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 507,
        stageId: "2G",
        title: "モノクロからの脱却",
        artist: "NAZO NEVERLAND",
        startTime: "18:50",
        endTime: "19:50",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 601,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "10:15",
        endTime: "10:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 602,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "11:00",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 603,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "11:45",
        endTime: "12:15",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 604,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 605,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "13:15",
        endTime: "13:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 606,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "14:00",
        endTime: "14:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 607,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "14:45",
        endTime: "15:15",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 608,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 609,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "16:15",
        endTime: "16:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 610,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "17:00",
        endTime: "17:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 611,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "17:45",
        endTime: "18:15",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 612,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "18:30",
        endTime: "19:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 613,
        stageId: "room201",
        title: "タイマー城からの脱出",
        artist: "早稲田大学謎解き企画algo",
        startTime: "19:15",
        endTime: "19:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 701,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "10:15",
        endTime: "11:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 702,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "11:15",
        endTime: "12:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 703,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "12:15",
        endTime: "13:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 704,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "13:45",
        endTime: "14:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 705,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "14:45",
        endTime: "15:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 706,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "15:45",
        endTime: "16:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 707,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "17:00",
        endTime: "17:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 708,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 709,
        stageId: "room202",
        title: "casual test",
        artist: "Shanow:R",
        startTime: "19:00",
        endTime: "19:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 801,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "10:30",
        endTime: "10:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 802,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "11:00",
        endTime: "11:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 803,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "11:30",
        endTime: "11:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 804,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "12:00",
        endTime: "12:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 805,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "12:30",
        endTime: "12:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 806,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "13:00",
        endTime: "13:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 807,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "13:30",
        endTime: "13:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 808,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "14:00",
        endTime: "14:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 809,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "14:30",
        endTime: "14:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 810,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "15:00",
        endTime: "15:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 811,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "15:30",
        endTime: "15:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 812,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "16:00",
        endTime: "16:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 813,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "16:30",
        endTime: "16:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 814,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "17:00",
        endTime: "17:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 815,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "17:30",
        endTime: "17:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 816,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "18:00",
        endTime: "18:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 817,
        stageId: "room203",
        title: "2006共通テスト総合問題",
        artist: "成田高校クイズ研究部",
        startTime: "18:30",
        endTime: "18:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 901,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "10:10",
        endTime: "11:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 902,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "11:15",
        endTime: "12:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 903,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "12:20",
        endTime: "13:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 904,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "13:45",
        endTime: "14:35",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 905,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "14:50",
        endTime: "15:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 906,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "15:55",
        endTime: "16:45",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 907,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "17:00",
        endTime: "17:50",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 908,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "18:05",
        endTime: "18:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 909,
        stageId: "room204",
        title: "NG ROokiE",
        artist: "埼玉大学謎解きサークル【site：Arcana】",
        startTime: "19:10",
        endTime: "20:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
    ],
};
