// ★このファイルはスプレッドシートから自動生成されます。手動編集は次回の出力で上書きされるので注意。
export default {
  title: "大阪最宴祭16 2日目 (2026/10/11)",
  startHour: 8,
  endHour: 24,
  blockMargin: 0,
  stages: [
    {
      id: "stage-1",
      name: "第1会議室",
      group: "浪速区民センター1F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-2",
      name: "第2会議室",
      group: "浪速区民センター1F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-3",
      name: "第3会議室",
      group: "浪速区民センター1F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-4",
      name: "第4会議室",
      group: "浪速区民センター2F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-5",
      name: "第5会議室",
      group: "浪速区民センター2F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-6",
      name: "和室①",
      group: "浪速区民センター2F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-7",
      name: "和室②",
      group: "浪速区民センター2F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-8",
      name: "第6会議室",
      group: "浪速区民センター3F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-9",
      name: "第7会議室",
      group: "浪速区民センター3F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-10",
      name: "第8会議室",
      group: "浪速区民センター3F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-11",
      name: "第9会議室",
      group: "浪速区民センター3F",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-12",
      name: "ステージ",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-13",
      name: "観客席",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-14",
      name: "倉庫",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-15",
      name: "ホールブース",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-16",
      name: "ホールブース",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-17",
      name: "ホールブース",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-18",
      name: "ホールブース",
      group: "浪速区民センター1F ホール",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-19",
      name: "ホールブース",
      group: "浪速区民センター1F ホール",
      allowMultiple: "TRUE",
      allowOverlap: "",
    },
    {
      id: "stage-20",
      name: "カフェ上",
      group: "レンタルスペース",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-21",
      name: "401",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-22",
      name: "403",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-23",
      name: "502",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-24",
      name: "601",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-25",
      name: "602",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
    {
      id: "stage-26",
      name: "701",
      group: "民泊",
      allowMultiple: "",
      allowOverlap: "",
    },
  ],
  schedules: [
    {
      id: 1,
      stageId: "stage-1",
      title: "VS",
      artist: "Melt",
      startTime: "10:30",
      endTime: "12:05",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 2,
      stageId: "stage-1",
      title: "VS",
      artist: "Melt",
      startTime: "12:45",
      endTime: "14:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 3,
      stageId: "stage-1",
      title: "VS",
      artist: "Melt",
      startTime: "15:00",
      endTime: "16:35",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 4,
      stageId: "stage-1",
      title: "VS",
      artist: "Melt",
      startTime: "17:15",
      endTime: "18:50",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 5,
      stageId: "stage-1",
      title: "VS",
      artist: "Melt",
      startTime: "19:30",
      endTime: "21:05",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 6,
      stageId: "stage-2",
      title: "チャレンジャー",
      artist: "大阪最宴祭運営",
      startTime: "10:30",
      endTime: "12:40",
      color: "bg-cyan-100 border-cyan-300",
      fee: "3500",
    },
    {
      id: 7,
      stageId: "stage-2",
      title: "チャレンジャー",
      artist: "大阪最宴祭運営",
      startTime: "13:20",
      endTime: "15:30",
      color: "bg-cyan-100 border-cyan-300",
      fee: "3500",
    },
    {
      id: 8,
      stageId: "stage-2",
      title: "チャレンジャー",
      artist: "大阪最宴祭運営",
      startTime: "16:10",
      endTime: "18:20",
      color: "bg-cyan-100 border-cyan-300",
      fee: "3500",
    },
    {
      id: 9,
      stageId: "stage-2",
      title: "チャレンジャー",
      artist: "大阪最宴祭運営",
      startTime: "19:00",
      endTime: "21:10",
      color: "bg-cyan-100 border-cyan-300",
      fee: "3500",
    },
    {
      id: 10,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "10:30",
      endTime: "11:15",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 11,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "11:45",
      endTime: "12:30",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 12,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "12:40",
      endTime: "13:25",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 13,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "13:35",
      endTime: "14:20",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 14,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "14:30",
      endTime: "15:15",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 15,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "15:35",
      endTime: "16:20",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 16,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "16:30",
      endTime: "17:15",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 17,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "17:25",
      endTime: "18:10",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 18,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "18:20",
      endTime: "19:05",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 19,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "19:25",
      endTime: "20:10",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 20,
      stageId: "stage-3",
      title: "Dさま!!7",
      artist: "Dさま!!制作委員会",
      startTime: "20:20",
      endTime: "21:05",
      color: "bg-teal-100 border-teal-300",
      fee: "2500",
    },
    {
      id: 21,
      stageId: "stage-4",
      title: "しょうたいこうえん",
      artist: "すぎやまいっぺぃ",
      startTime: "10:30",
      endTime: "12:00",
      color: "bg-green-100 border-green-300",
      fee: "3000",
    },
    {
      id: 22,
      stageId: "stage-4",
      title: "しょうたいこうえん",
      artist: "すぎやまいっぺぃ",
      startTime: "12:30",
      endTime: "14:00",
      color: "bg-green-100 border-green-300",
      fee: "3000",
    },
    {
      id: 23,
      stageId: "stage-4",
      title: "しょうたいこうえん",
      artist: "すぎやまいっぺぃ",
      startTime: "15:00",
      endTime: "16:30",
      color: "bg-green-100 border-green-300",
      fee: "3000",
    },
    {
      id: 24,
      stageId: "stage-4",
      title: "しょうたいこうえん",
      artist: "すぎやまいっぺぃ",
      startTime: "17:00",
      endTime: "18:30",
      color: "bg-green-100 border-green-300",
      fee: "3000",
    },
    {
      id: 25,
      stageId: "stage-5",
      title: "NoA Presents",
      artist: "NoA",
      startTime: "10:30",
      endTime: "12:40",
      color: "bg-amber-100 border-amber-300",
      fee: "3500",
    },
    {
      id: 26,
      stageId: "stage-5",
      title: "NoA Presents",
      artist: "NoA",
      startTime: "13:30",
      endTime: "15:40",
      color: "bg-amber-100 border-amber-300",
      fee: "3500",
    },
    {
      id: 27,
      stageId: "stage-5",
      title: "NoA Presents",
      artist: "NoA",
      startTime: "16:00",
      endTime: "18:10",
      color: "bg-amber-100 border-amber-300",
      fee: "3500",
    },
    {
      id: 28,
      stageId: "stage-5",
      title: "NoA Presents",
      artist: "NoA",
      startTime: "18:30",
      endTime: "20:40",
      color: "bg-amber-100 border-amber-300",
      fee: "3500",
    },
    {
      id: 29,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "10:30",
      endTime: "11:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 30,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "11:10",
      endTime: "11:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 31,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "11:50",
      endTime: "12:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 32,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "12:30",
      endTime: "13:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 33,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "13:10",
      endTime: "13:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 34,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "13:50",
      endTime: "14:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 35,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "14:30",
      endTime: "15:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 36,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "15:10",
      endTime: "15:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 37,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "15:50",
      endTime: "16:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 38,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "16:30",
      endTime: "17:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 39,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "17:10",
      endTime: "17:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 40,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "17:50",
      endTime: "18:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 41,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "18:30",
      endTime: "19:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 42,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "19:10",
      endTime: "19:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 43,
      stageId: "stage-6",
      title: "ワードミュージアム4",
      artist: "TKGデラックス",
      startTime: "19:50",
      endTime: "20:20",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 44,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "10:30",
      endTime: "11:40",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 45,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "12:00",
      endTime: "13:10",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 46,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "13:30",
      endTime: "14:40",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 47,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "15:00",
      endTime: "16:10",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 48,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "16:30",
      endTime: "17:40",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 49,
      stageId: "stage-7",
      title: "閃!!謎解塾",
      artist: "うみのくるしみゲームス",
      startTime: "18:00",
      endTime: "19:10",
      color: "bg-red-100 border-red-300",
      fee: "2500",
    },
    {
      id: 50,
      stageId: "stage-8",
      title: "EmoTE STructure",
      artist: "空空-karakara-",
      startTime: "10:30",
      endTime: "12:05",
      color: "bg-lime-100 border-lime-300",
      fee: "4000",
    },
    {
      id: 51,
      stageId: "stage-8",
      title: "EmoTE STructure",
      artist: "空空-karakara-",
      startTime: "12:30",
      endTime: "14:05",
      color: "bg-lime-100 border-lime-300",
      fee: "4000",
    },
    {
      id: 52,
      stageId: "stage-8",
      title: "EmoTE STructure",
      artist: "空空-karakara-",
      startTime: "14:30",
      endTime: "16:05",
      color: "bg-lime-100 border-lime-300",
      fee: "4000",
    },
    {
      id: 53,
      stageId: "stage-8",
      title: "EmoTE STructure",
      artist: "空空-karakara-",
      startTime: "16:30",
      endTime: "18:05",
      color: "bg-lime-100 border-lime-300",
      fee: "4000",
    },
    {
      id: 54,
      stageId: "stage-8",
      title: "EmoTE STructure",
      artist: "空空-karakara-",
      startTime: "18:30",
      endTime: "20:05",
      color: "bg-lime-100 border-lime-300",
      fee: "4000",
    },
    {
      id: 55,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "10:30",
      endTime: "11:20",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 56,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "11:30",
      endTime: "12:20",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 57,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "13:00",
      endTime: "13:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 58,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "14:00",
      endTime: "14:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 59,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "15:00",
      endTime: "15:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 60,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "16:00",
      endTime: "16:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 61,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "17:00",
      endTime: "17:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 62,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "18:00",
      endTime: "18:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 63,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "19:00",
      endTime: "19:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 64,
      stageId: "stage-9",
      title: "不正だらけの入試からの脱出",
      artist: "OUtfoX",
      startTime: "20:00",
      endTime: "20:50",
      color: "bg-blue-100 border-blue-300",
      fee: "1000",
    },
    {
      id: 65,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "10:30",
      endTime: "11:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 66,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "11:30",
      endTime: "12:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 67,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "12:30",
      endTime: "13:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 68,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "13:30",
      endTime: "14:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 69,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "14:30",
      endTime: "15:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 70,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "15:30",
      endTime: "16:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 71,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "16:30",
      endTime: "17:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 72,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "17:30",
      endTime: "18:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 73,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "18:30",
      endTime: "19:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 74,
      stageId: "stage-10",
      title: "ALL IS BALLs",
      artist: "teaparty",
      startTime: "19:30",
      endTime: "20:10",
      color: "bg-teal-100 border-teal-300",
      fee: "1500",
    },
    {
      id: 75,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "10:30",
      endTime: "11:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 76,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "11:10",
      endTime: "11:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 77,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "11:50",
      endTime: "12:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 78,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "12:30",
      endTime: "13:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 79,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "13:10",
      endTime: "13:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 80,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "13:50",
      endTime: "14:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 81,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "15:10",
      endTime: "15:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 82,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "15:50",
      endTime: "16:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 83,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "16:30",
      endTime: "17:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 84,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "17:10",
      endTime: "17:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 85,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "17:50",
      endTime: "18:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 86,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "18:30",
      endTime: "19:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 87,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "19:10",
      endTime: "19:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 88,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "19:50",
      endTime: "20:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 89,
      stageId: "stage-11",
      title: "かけめぐれ！ムリヤリセイトンスケルトン",
      artist: "NAZONE",
      startTime: "20:30",
      endTime: "21:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2000",
    },
    {
      id: 90,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "10:30",
      endTime: "10:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 91,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "11:00",
      endTime: "11:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 92,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "11:30",
      endTime: "11:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 93,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "12:00",
      endTime: "12:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 94,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "12:30",
      endTime: "12:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 95,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "13:00",
      endTime: "13:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 96,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "13:30",
      endTime: "13:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 97,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "14:00",
      endTime: "14:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 98,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "14:30",
      endTime: "14:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 99,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "15:30",
      endTime: "15:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 100,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "16:00",
      endTime: "16:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 101,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "16:30",
      endTime: "16:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 102,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "17:00",
      endTime: "17:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 103,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "17:30",
      endTime: "17:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 104,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "18:00",
      endTime: "18:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 105,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "18:30",
      endTime: "18:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 106,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "19:00",
      endTime: "19:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 107,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "19:30",
      endTime: "19:55",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 108,
      stageId: "stage-12",
      title: "うつるんです！",
      artist: "マダミステリ屋",
      startTime: "20:00",
      endTime: "20:25",
      color: "bg-yellow-100 border-yellow-300",
      fee: "1000",
    },
    {
      id: 109,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "10:30",
      endTime: "11:05",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 110,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "11:15",
      endTime: "11:50",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 111,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "12:00",
      endTime: "12:35",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 112,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "12:45",
      endTime: "13:20",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 113,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "13:30",
      endTime: "14:05",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 114,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "14:45",
      endTime: "15:20",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 115,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "15:30",
      endTime: "16:05",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 116,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "16:15",
      endTime: "16:50",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 117,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "17:00",
      endTime: "17:35",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 118,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "18:15",
      endTime: "18:50",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 119,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "19:00",
      endTime: "19:35",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 120,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "19:45",
      endTime: "20:20",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 121,
      stageId: "stage-13",
      title: "観客席",
      artist: "Flambeur's Coin",
      startTime: "20:30",
      endTime: "21:05",
      color: "bg-blue-100 border-blue-300",
      fee: "2000",
    },
    {
      id: 122,
      stageId: "stage-14",
      title: "メダル×パネル→アイテム！",
      artist: "uranariya",
      startTime: "10:30",
      endTime: "11:05",
      color: "bg-indigo-100 border-indigo-300",
      fee: "1000",
    },
    {
      id: 123,
      stageId: "stage-14",
      title: "メダル×パネル→アイテム！",
      artist: "uranariya",
      startTime: "11:15",
      endTime: "11:50",
      color: "bg-indigo-100 border-indigo-300",
      fee: "1000",
    },
    {
      id: 124,
      stageId: "stage-14",
      title: "メダル×パネル→アイテム！",
      artist: "uranariya",
      startTime: "12:00",
      endTime: "12:35",
      color: "bg-indigo-100 border-indigo-300",
      fee: "1000",
    },
    {
      id: 125,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "10:30",
      endTime: "11:10",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 126,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "11:20",
      endTime: "12:00",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 127,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "12:10",
      endTime: "12:50",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 128,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "13:00",
      endTime: "13:40",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 129,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "13:50",
      endTime: "14:30",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 130,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "14:40",
      endTime: "15:20",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 131,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "15:30",
      endTime: "16:10",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 132,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "16:20",
      endTime: "17:00",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 133,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "17:10",
      endTime: "17:50",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 134,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "18:00",
      endTime: "18:40",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 135,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "18:50",
      endTime: "19:30",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 136,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "19:40",
      endTime: "20:20",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 137,
      stageId: "stage-15",
      title: "無限に□□□が続く塔",
      artist: "ドリム",
      startTime: "20:30",
      endTime: "21:10",
      color: "bg-cyan-100 border-cyan-300",
      fee: "2000",
    },
    {
      id: 138,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "10:30",
      endTime: "11:30",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 139,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "12:00",
      endTime: "13:00",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 140,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "13:30",
      endTime: "14:30",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 141,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "15:00",
      endTime: "16:00",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 142,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "16:30",
      endTime: "17:30",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 143,
      stageId: "stage-16",
      title: "FLOW",
      artist: "モノマニアック",
      startTime: "18:00",
      endTime: "19:00",
      color: "bg-teal-100 border-teal-300",
      fee: "2000",
    },
    {
      id: 144,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "10:30",
      endTime: "11:10",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 145,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "11:30",
      endTime: "12:10",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 146,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "12:30",
      endTime: "13:10",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 147,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "13:30",
      endTime: "14:10",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 148,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "14:50",
      endTime: "15:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 149,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "15:50",
      endTime: "16:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 150,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "16:50",
      endTime: "17:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 151,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "18:00",
      endTime: "18:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 152,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "19:00",
      endTime: "19:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 153,
      stageId: "stage-17",
      title: "シンドバッドと無限の宝物庫",
      artist: "ナゾトキ番長",
      startTime: "20:00",
      endTime: "20:40",
      color: "bg-yellow-100 border-yellow-300",
      fee: "2000",
    },
    {
      id: 154,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "10:30",
      endTime: "11:20",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 155,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "11:40",
      endTime: "12:30",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 156,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "12:50",
      endTime: "13:40",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 157,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "14:00",
      endTime: "14:50",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 158,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "15:10",
      endTime: "16:00",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 159,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "16:20",
      endTime: "17:10",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 160,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "17:30",
      endTime: "18:20",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 161,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "18:40",
      endTime: "19:30",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 162,
      stageId: "stage-18",
      title: "私物の使用は可能です",
      artist: "CrossXOne",
      startTime: "19:50",
      endTime: "20:40",
      color: "bg-lime-100 border-lime-300",
      fee: "2000",
    },
    {
      id: 163,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "10:30",
      endTime: "10:55",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 164,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "11:00",
      endTime: "11:25",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 165,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "11:40",
      endTime: "12:05",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 166,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "12:10",
      endTime: "12:35",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 167,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "13:10",
      endTime: "13:35",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 168,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "13:40",
      endTime: "14:05",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 169,
      stageId: "stage-19",
      title:
        "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム ※2回目優先",
      artist: "BABEL",
      startTime: "14:30",
      endTime: "14:55",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 170,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "15:00",
      endTime: "15:25",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 171,
      stageId: "stage-19",
      title:
        "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム ※2回目優先",
      artist: "BABEL",
      startTime: "15:50",
      endTime: "16:15",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 172,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "16:20",
      endTime: "16:45",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 173,
      stageId: "stage-19",
      title:
        "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム ※2回目優先",
      artist: "BABEL",
      startTime: "17:30",
      endTime: "17:55",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 174,
      stageId: "stage-19",
      title: "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム",
      artist: "BABEL",
      startTime: "18:00",
      endTime: "18:25",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 175,
      stageId: "stage-19",
      title:
        "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム ※2回目優先",
      artist: "BABEL",
      startTime: "19:00",
      endTime: "19:25",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 176,
      stageId: "stage-19",
      title:
        "【事前予約なし】それなりにシンプルでお手軽な脱出ゲーム ※2回目優先",
      artist: "BABEL",
      startTime: "19:30",
      endTime: "19:55",
      color: "bg-green-100 border-green-300",
      fee: "2000",
    },
    {
      id: 177,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "9:30",
      endTime: "10:20",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 178,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "10:30",
      endTime: "11:20",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 179,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "11:30",
      endTime: "12:20",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 180,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "12:30",
      endTime: "13:20",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 181,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "13:30",
      endTime: "14:20",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 182,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "14:40",
      endTime: "15:30",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 183,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "15:40",
      endTime: "16:30",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 184,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "16:40",
      endTime: "17:30",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 185,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "17:40",
      endTime: "18:30",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 186,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "18:50",
      endTime: "19:40",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 187,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "19:50",
      endTime: "20:40",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 188,
      stageId: "stage-20",
      title: "孤独な謎と被検体.",
      artist: "algo",
      startTime: "20:50",
      endTime: "21:40",
      color: "bg-amber-100 border-amber-300",
      fee: "2500",
    },
    {
      id: 189,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "10:30",
      endTime: "11:00",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 190,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "11:10",
      endTime: "11:40",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 191,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "11:50",
      endTime: "12:20",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 192,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "12:30",
      endTime: "13:00",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 193,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "13:40",
      endTime: "14:10",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 194,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "14:20",
      endTime: "14:50",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 195,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "15:00",
      endTime: "15:30",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 196,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "15:40",
      endTime: "16:10",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 197,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "16:50",
      endTime: "17:20",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 198,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "17:30",
      endTime: "18:00",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 199,
      stageId: "stage-21",
      title: "＜EX前売り切れ＞1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "18:10",
      endTime: "18:40",
      color: "bg-gray-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 200,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "18:50",
      endTime: "19:20",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 201,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "19:30",
      endTime: "20:00",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 202,
      stageId: "stage-21",
      title: "1000億ローゼを盗み出せ！",
      artist: "0001（ゼロイチ）",
      startTime: "20:10",
      endTime: "20:40",
      color: "bg-orange-100 border-orange-300",
      fee: "2000",
    },
    {
      id: 203,
      stageId: "stage-22",
      title: "ENDLESS TRAIN",
      artist: "ネコノヨスガ",
      startTime: "8:45",
      endTime: "10:20",
      color: "bg-lime-100 border-lime-300",
      fee: "3000",
    },
    {
      id: 204,
      stageId: "stage-22",
      title: "ENDLESS TRAIN",
      artist: "ネコノヨスガ",
      startTime: "12:20",
      endTime: "13:55",
      color: "bg-lime-100 border-lime-300",
      fee: "3000",
    },
    {
      id: 205,
      stageId: "stage-22",
      title: "ENDLESS TRAIN",
      artist: "ネコノヨスガ",
      startTime: "15:10",
      endTime: "16:45",
      color: "bg-lime-100 border-lime-300",
      fee: "3000",
    },
    {
      id: 206,
      stageId: "stage-22",
      title: "ENDLESS TRAIN",
      artist: "ネコノヨスガ",
      startTime: "17:50",
      endTime: "19:25",
      color: "bg-lime-100 border-lime-300",
      fee: "3000",
    },
    {
      id: 207,
      stageId: "stage-22",
      title: "ENDLESS TRAIN",
      artist: "ネコノヨスガ",
      startTime: "21:10",
      endTime: "22:45",
      color: "bg-lime-100 border-lime-300",
      fee: "3000",
    },
    {
      id: 208,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "10:30",
      endTime: "11:20",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 209,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "11:30",
      endTime: "12:20",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 210,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "12:30",
      endTime: "13:20",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 211,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "13:30",
      endTime: "14:20",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 212,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "14:30",
      endTime: "15:20",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 213,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "16:00",
      endTime: "16:50",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 214,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "17:00",
      endTime: "17:50",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 215,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "18:00",
      endTime: "18:50",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 216,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "19:00",
      endTime: "19:50",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 217,
      stageId: "stage-23",
      title: "特命0",
      artist: "Flambeur's Coin",
      startTime: "20:00",
      endTime: "20:50",
      color: "bg-blue-100 border-blue-300",
      fee: "3000",
    },
    {
      id: 218,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "9:40",
      endTime: "10:40",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 219,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "10:50",
      endTime: "11:50",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 220,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "12:00",
      endTime: "13:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 221,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "13:10",
      endTime: "14:10",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 222,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "14:20",
      endTime: "15:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 223,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "15:30",
      endTime: "16:30",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 224,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "16:50",
      endTime: "17:50",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 225,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "18:00",
      endTime: "19:00",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 226,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "19:10",
      endTime: "20:10",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 227,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "20:20",
      endTime: "21:20",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 228,
      stageId: "stage-24",
      title: "【LAST STEP】なぜ成功できたのか",
      artist: "彩Riddle",
      startTime: "21:30",
      endTime: "22:30",
      color: "bg-pink-100 border-pink-300",
      fee: "2500",
    },
    {
      id: 229,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "9:00",
      endTime: "10:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 230,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "10:30",
      endTime: "11:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 231,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "12:00",
      endTime: "13:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 232,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "13:30",
      endTime: "14:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 233,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "15:00",
      endTime: "16:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 234,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "16:30",
      endTime: "17:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 235,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "18:00",
      endTime: "19:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 236,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "19:30",
      endTime: "20:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 237,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "21:00",
      endTime: "22:00",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 238,
      stageId: "stage-25",
      title: "ポイすてっ！2",
      artist: "RI:Works",
      startTime: "22:30",
      endTime: "23:30",
      color: "bg-yellow-100 border-yellow-300",
      fee: "3000",
    },
    {
      id: 239,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "8:00",
      endTime: "9:00",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 240,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "9:20",
      endTime: "10:20",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 241,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "10:40",
      endTime: "11:40",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 242,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "12:20",
      endTime: "13:20",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 243,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "13:40",
      endTime: "14:40",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 244,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "15:00",
      endTime: "16:00",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 245,
      stageId: "stage-26",
      title: "There's Answer",
      artist: "Leia",
      startTime: "16:20",
      endTime: "17:20",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3000",
    },
    {
      id: 246,
      stageId: "stage-26",
      title: "There's Answer（ロングタイム回）",
      artist: "Leia",
      startTime: "18:00",
      endTime: "19:10",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3500",
    },
    {
      id: 247,
      stageId: "stage-26",
      title: "There's Answer（ロングタイム回）",
      artist: "Leia",
      startTime: "19:30",
      endTime: "20:40",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3500",
    },
    {
      id: 248,
      stageId: "stage-26",
      title: "There's Answer（ロングタイム回）",
      artist: "Leia",
      startTime: "21:00",
      endTime: "22:10",
      color: "bg-indigo-100 border-indigo-300",
      fee: "3500",
    },
  ],
};
