// ★このファイルはスプレッドシート（AppScript.txt の exportToTypeScript）から自動生成される。手動編集は次回の出力で上書きされるので注意。
export default {
    title: "大阪最宴祭15 1日目 (2026/6/20)",
    startHour: 8,
    endHour: 24,
    blockMargin: 0,
    stages: [
      {
        id: "stage-1",
        name: "第1会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-2",
        name: "第2会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-3",
        name: "第3会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-4",
        name: "第4会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-5",
        name: "第5会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-6",
        name: "和室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-9",
        name: "第6会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-10",
        name: "第7会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-11",
        name: "第8,9会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-12",
        name: "ステージ①",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-13",
        name: "ステージ②",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-14",
        name: "観客席",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-16",
        name: "倉庫",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17a",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17b",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17c",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17d",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17e",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17f",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17g",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-18",
        name: "カフェ上",
        group: "レンタルスペース",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-19",
        name: "401",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-20",
        name: "403",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-21",
        name: "502",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-22",
        name: "601",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-23",
        name: "602①",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-24",
        name: "602②",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-25",
        name: "701",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-26",
        name: "702",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-27",
        name: "2F",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-28",
        name: "3F",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-29",
        name: "4F①",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-30",
        name: "4F②",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
    ],
    schedules: [
      {
        id: 1,
        stageId: "stage-1",
        title: "＜通常前売り切れ＞タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-gray-100 border-red-300",
        fee: "2500",
      },
      {
        id: 2,
        stageId: "stage-1",
        title: "＜通常前売り切れ＞タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-gray-100 border-red-300",
        fee: "2500",
      },
      {
        id: 3,
        stageId: "stage-1",
        title: "＜通常前売り切れ＞タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "13:20",
        endTime: "14:20",
        color: "bg-gray-100 border-red-300",
        fee: "2500",
      },
      {
        id: 4,
        stageId: "stage-1",
        title: "＜通常前売り切れ＞タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-gray-100 border-red-300",
        fee: "2500",
      },
      {
        id: 5,
        stageId: "stage-1",
        title: "＜通常前売り切れ＞タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "16:00",
        endTime: "17:00",
        color: "bg-gray-100 border-red-300",
        fee: "2500",
      },
      {
        id: 6,
        stageId: "stage-1",
        title: "タンクトップバトラー！袖無",
        artist: "ShareKOBE",
        startTime: "17:20",
        endTime: "18:20",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 12,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "10:30",
        endTime: "12:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 13,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "12:30",
        endTime: "14:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 14,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "14:30",
        endTime: "16:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 15,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "16:30",
        endTime: "18:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 16,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "18:30",
        endTime: "20:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 22,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 23,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 24,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 25,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 26,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 27,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "13:50",
        endTime: "14:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 28,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "15:00",
        endTime: "15:30",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 29,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "15:40",
        endTime: "16:10",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 30,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "16:20",
        endTime: "16:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 31,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "17:00",
        endTime: "17:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 32,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "17:40",
        endTime: "18:10",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 33,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "18:20",
        endTime: "18:50",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 34,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "19:00",
        endTime: "19:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 35,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "19:40",
        endTime: "20:10",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 36,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "20:20",
        endTime: "20:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 51,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 52,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "12:45",
        endTime: "14:15",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 53,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "15:00",
        endTime: "16:30",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 54,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "17:00",
        endTime: "18:30",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 55,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "19:00",
        endTime: "20:30",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 56,
        stageId: "stage-4",
        title: "J0001N US!",
        artist: "0001（ゼロイチ）",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 65,
        stageId: "stage-5",
        title: "めざせ！S級はしご建築士",
        artist: "EscaPLUGGED",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-lime-100 border-lime-300",
        fee: "3000",
      },
      {
        id: 66,
        stageId: "stage-5",
        title: "めざせ！S級はしご建築士",
        artist: "EscaPLUGGED",
        startTime: "12:30",
        endTime: "14:00",
        color: "bg-lime-100 border-lime-300",
        fee: "3000",
      },
      {
        id: 67,
        stageId: "stage-5",
        title: "めざせ！S級はしご建築士",
        artist: "EscaPLUGGED",
        startTime: "14:30",
        endTime: "16:00",
        color: "bg-lime-100 border-lime-300",
        fee: "3000",
      },
      {
        id: 68,
        stageId: "stage-5",
        title: "めざせ！S級はしご建築士",
        artist: "EscaPLUGGED",
        startTime: "16:30",
        endTime: "18:00",
        color: "bg-lime-100 border-lime-300",
        fee: "3000",
      },
      {
        id: 72,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 73,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "12:15",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 74,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "14:00",
        endTime: "15:30",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 75,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "15:45",
        endTime: "17:15",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 76,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "17:30",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 77,
        stageId: "stage-6",
        title: "完勝ウィザードリル",
        artist: "よよまる",
        startTime: "19:15",
        endTime: "20:45",
        color: "bg-teal-100 border-teal-300",
        fee: "3000",
      },
      {
        id: 100,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 101,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "11:45",
        endTime: "12:45",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 102,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "13:00",
        endTime: "14:00",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 103,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "14:15",
        endTime: "15:15",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 104,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "15:30",
        endTime: "16:30",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 105,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "16:45",
        endTime: "17:45",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 106,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 107,
        stageId: "stage-9",
        title: "DEATH GAME",
        artist: "Toy×ボーズ",
        startTime: "19:15",
        endTime: "20:15",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 120,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 121,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "11:45",
        endTime: "12:30",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 122,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 123,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "14:15",
        endTime: "15:00",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 124,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 125,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "16:45",
        endTime: "17:30",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 126,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 127,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "19:15",
        endTime: "20:00",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 136,
        stageId: "stage-11",
        title: "ぼったくりメイド喫茶からの脱出",
        artist: "Tri Möbius",
        startTime: "11:00",
        endTime: "12:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "3500",
      },
      {
        id: 137,
        stageId: "stage-11",
        title: "ぼったくりメイド喫茶からの脱出",
        artist: "Tri Möbius",
        startTime: "13:50",
        endTime: "15:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "3500",
      },
      {
        id: 138,
        stageId: "stage-11",
        title: "ぼったくりメイド喫茶からの脱出",
        artist: "Tri Möbius",
        startTime: "16:10",
        endTime: "17:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "3500",
      },
      {
        id: 139,
        stageId: "stage-11",
        title: "ぼったくりメイド喫茶からの脱出",
        artist: "Tri Möbius",
        startTime: "18:30",
        endTime: "20:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "3500",
      },
      {
        id: 144,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 145,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 146,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 147,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 148,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "14:50",
        endTime: "15:30",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 149,
        stageId: "stage-12",
        title: "＜通常前売り切れ＞リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "15:50",
        endTime: "16:30",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 150,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "16:50",
        endTime: "17:30",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 151,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "18:00",
        endTime: "18:40",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 152,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "19:00",
        endTime: "19:40",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 153,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "20:00",
        endTime: "20:40",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 161,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "10:30",
        endTime: "10:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 162,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "11:00",
        endTime: "11:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 163,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "11:30",
        endTime: "11:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 164,
        stageId: "stage-13",
        title: "＜通常前売り切れ＞うつるんです！",
        artist: "マダミステリ屋",
        startTime: "12:00",
        endTime: "12:25",
        color: "bg-gray-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 165,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "13:00",
        endTime: "13:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 166,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "13:30",
        endTime: "13:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 167,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "14:00",
        endTime: "14:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 168,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "14:30",
        endTime: "14:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 169,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "15:00",
        endTime: "15:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 170,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "16:00",
        endTime: "16:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 171,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "16:30",
        endTime: "16:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 172,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "17:00",
        endTime: "17:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 173,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "17:30",
        endTime: "17:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 174,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "18:30",
        endTime: "18:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 175,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "19:00",
        endTime: "19:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 176,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "19:30",
        endTime: "19:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 177,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "20:00",
        endTime: "20:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 178,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "20:30",
        endTime: "20:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 191,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "10:30",
        endTime: "11:05",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 192,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "11:15",
        endTime: "11:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 193,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "12:10",
        endTime: "12:45",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 194,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "12:55",
        endTime: "13:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 195,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "13:40",
        endTime: "14:15",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 196,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "14:25",
        endTime: "15:00",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 197,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "15:15",
        endTime: "15:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 198,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "16:00",
        endTime: "16:35",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 199,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "16:45",
        endTime: "17:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 200,
        stageId: "stage-14",
        title: "観客席",
        artist: "Flambeur’s Coin",
        startTime: "17:30",
        endTime: "18:05",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 201,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "18:15",
        endTime: "18:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 202,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "19:00",
        endTime: "19:35",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 203,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "19:45",
        endTime: "20:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 204,
        stageId: "stage-14",
        title: "＜通常前売り切れ＞観客席",
        artist: "Flambeur’s Coin",
        startTime: "20:25",
        endTime: "21:00",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 206,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 207,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "11:30",
        endTime: "12:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 208,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "12:30",
        endTime: "13:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 209,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "13:30",
        endTime: "14:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 210,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 211,
        stageId: "stage-16",
        title: "＜通常前売り切れ＞彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-gray-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 212,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "17:30",
        endTime: "18:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 213,
        stageId: "stage-16",
        title: "彷徨える怪物からの脱出",
        artist: "uranariya",
        startTime: "18:30",
        endTime: "19:15",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 219,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 220,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 221,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 222,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 223,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "15:00",
        endTime: "15:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 224,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "16:00",
        endTime: "16:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 225,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "17:00",
        endTime: "17:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 226,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "18:00",
        endTime: "18:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 227,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "19:00",
        endTime: "19:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 228,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "20:00",
        endTime: "20:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 238,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "10:30",
        endTime: "11:05",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 239,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "11:20",
        endTime: "11:55",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 240,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "12:10",
        endTime: "12:45",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 241,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "13:00",
        endTime: "13:35",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 242,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "13:50",
        endTime: "14:25",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 243,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "14:40",
        endTime: "15:15",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 244,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "15:30",
        endTime: "16:05",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 245,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "16:20",
        endTime: "16:55",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 246,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "17:10",
        endTime: "17:45",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 247,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "18:00",
        endTime: "18:35",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 248,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "18:50",
        endTime: "19:25",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 249,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "19:40",
        endTime: "20:15",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 250,
        stageId: "stage-17b",
        title: "-52-",
        artist: "Melt",
        startTime: "20:30",
        endTime: "21:05",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 260,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 261,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "11:20",
        endTime: "12:00",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 262,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "12:10",
        endTime: "12:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 263,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "13:00",
        endTime: "13:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 264,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "14:10",
        endTime: "14:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 265,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "15:00",
        endTime: "15:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 266,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "15:50",
        endTime: "16:30",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 267,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "16:40",
        endTime: "17:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 268,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 269,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "18:20",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 270,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "19:10",
        endTime: "19:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 271,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "20:00",
        endTime: "20:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 284,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 285,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "12:15",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 286,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "14:00",
        endTime: "15:30",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 287,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "15:45",
        endTime: "17:15",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 288,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "17:30",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 289,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "19:15",
        endTime: "20:45",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 296,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 297,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 298,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 299,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "13:00",
        endTime: "13:30",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 300,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "13:40",
        endTime: "14:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 301,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "14:20",
        endTime: "14:50",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 302,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "15:00",
        endTime: "15:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 303,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "15:40",
        endTime: "16:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 304,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "16:40",
        endTime: "17:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 305,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "17:20",
        endTime: "17:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 306,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "18:00",
        endTime: "18:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 307,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "19:00",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 308,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "19:40",
        endTime: "20:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 309,
        stageId: "stage-17e",
        title: "超熱狂ひらめきバトル!! 99枚の皿６",
        artist: "ＴＫＧデラックス",
        startTime: "20:20",
        endTime: "20:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 325,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 326,
        stageId: "stage-17f",
        title: "＜通常前売り切れ＞ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "11:20",
        endTime: "12:00",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 327,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "12:10",
        endTime: "12:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 328,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "13:00",
        endTime: "13:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 329,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "13:50",
        endTime: "14:30",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 330,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "14:40",
        endTime: "15:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 331,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 332,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "16:20",
        endTime: "17:00",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 333,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "17:10",
        endTime: "17:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 334,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "18:00",
        endTime: "18:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 335,
        stageId: "stage-17f",
        title: "ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "18:50",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 336,
        stageId: "stage-17f",
        title: "＜通常前売り切れ＞ハッタリハッタリ",
        artist: "ComeCozy",
        startTime: "19:40",
        endTime: "20:20",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 345,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "10:30",
        endTime: "10:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 346,
        stageId: "stage-17g",
        title: "＜通常前売り切れ＞まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "11:00",
        endTime: "11:20",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 347,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "11:30",
        endTime: "11:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 348,
        stageId: "stage-17g",
        title: "＜通常前売り切れ＞まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "12:00",
        endTime: "12:20",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 349,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "12:30",
        endTime: "12:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 350,
        stageId: "stage-17g",
        title: "＜通常前売り切れ＞まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:30",
        endTime: "13:50",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 351,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "14:00",
        endTime: "14:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 352,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "14:30",
        endTime: "14:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 353,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:00",
        endTime: "15:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 354,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:30",
        endTime: "15:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 355,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "16:30",
        endTime: "16:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 356,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "17:00",
        endTime: "17:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 357,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "17:30",
        endTime: "17:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 358,
        stageId: "stage-17g",
        title: "＜通常前売り切れ＞まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:00",
        endTime: "18:20",
        color: "bg-gray-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 359,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:30",
        endTime: "18:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 360,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "19:00",
        endTime: "19:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 361,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "19:30",
        endTime: "19:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 362,
        stageId: "stage-17g",
        title: "まっきー1本謎のもと",
        artist: "すぎやまっきー",
        startTime: "20:00",
        endTime: "20:20",
        color: "bg-teal-100 border-teal-300",
        fee: "1000",
      },
      {
        id: 369,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "9:30",
        endTime: "10:20",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 370,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 371,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 372,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 373,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "13:30",
        endTime: "14:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 374,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "14:40",
        endTime: "15:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 375,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "15:40",
        endTime: "16:30",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 376,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "16:40",
        endTime: "17:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 377,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "17:40",
        endTime: "18:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 378,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "18:50",
        endTime: "19:40",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 379,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 380,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "20:50",
        endTime: "21:40",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 393,
        stageId: "stage-19",
        title: "＜通常前売り切れ＞YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "10:00",
        endTime: "10:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 394,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 395,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 396,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 397,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 398,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "15:00",
        endTime: "15:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 399,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 400,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "17:00",
        endTime: "17:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 401,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 402,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "19:00",
        endTime: "19:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 413,
        stageId: "stage-20",
        title: "＜通常前売り切れ＞人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "9:00",
        endTime: "10:25",
        color: "bg-gray-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 414,
        stageId: "stage-20",
        title: "＜通常前売り切れ＞人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "10:50",
        endTime: "12:15",
        color: "bg-gray-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 415,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "12:40",
        endTime: "14:05",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 416,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "14:40",
        endTime: "16:05",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 417,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "16:30",
        endTime: "17:55",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 418,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "18:20",
        endTime: "19:45",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 419,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "20:10",
        endTime: "21:35",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 427,
        stageId: "stage-21",
        title: "＜通常前売り切れ＞住人と居ろ！",
        artist: "Quattrophy",
        startTime: "9:00",
        endTime: "9:45",
        color: "bg-gray-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 428,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "10:00",
        endTime: "10:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 429,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 430,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 431,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 432,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 433,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "15:00",
        endTime: "15:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 434,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 435,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "17:00",
        endTime: "17:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 436,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 437,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "19:00",
        endTime: "19:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 438,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "20:00",
        endTime: "20:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 439,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "21:00",
        endTime: "21:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 448,
        stageId: "stage-22",
        title: "＜売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "9:40",
        endTime: "10:40",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 449,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "10:50",
        endTime: "11:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 450,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 451,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "13:10",
        endTime: "14:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 452,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "14:20",
        endTime: "15:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 453,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "15:30",
        endTime: "16:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 454,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "16:50",
        endTime: "17:50",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 455,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 456,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "19:10",
        endTime: "20:10",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 457,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "20:20",
        endTime: "21:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 458,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "21:30",
        endTime: "22:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 470,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 471,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 472,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 473,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 474,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 475,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 476,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 477,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 478,
        stageId: "stage-23",
        title: "＜通常前売り切れ＞対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 479,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 490,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 491,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 492,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 493,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 494,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 495,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 496,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 497,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 498,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 499,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 510,
        stageId: "stage-25",
        title: "＜通常前売り切れ＞staQube",
        artist: "あかいちゃり",
        startTime: "9:30",
        endTime: "10:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 511,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 512,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 513,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 514,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "14:30",
        endTime: "15:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 515,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 516,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "16:30",
        endTime: "17:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 517,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 518,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "18:30",
        endTime: "19:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 519,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "20:30",
        endTime: "21:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 520,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "21:30",
        endTime: "22:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 530,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "10:10",
        endTime: "11:00",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 531,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "11:10",
        endTime: "12:00",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 532,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "13:00",
        endTime: "13:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 533,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 534,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "15:00",
        endTime: "15:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 535,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "16:00",
        endTime: "16:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 536,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "17:00",
        endTime: "17:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 537,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "18:00",
        endTime: "18:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 538,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "19:00",
        endTime: "19:50",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 539,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "20:10",
        endTime: "21:00",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 548,
        stageId: "stage-27",
        title: "＜通常前売り切れ＞Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "9:50",
        endTime: "10:20",
        color: "bg-gray-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 549,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "10:40",
        endTime: "11:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 550,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "11:30",
        endTime: "12:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 551,
        stageId: "stage-27",
        title: "＜通常前売り切れ＞Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "12:20",
        endTime: "12:50",
        color: "bg-gray-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 552,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 553,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "14:00",
        endTime: "14:30",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 554,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "14:50",
        endTime: "15:20",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 555,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "15:40",
        endTime: "16:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 556,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "16:30",
        endTime: "17:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 557,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "17:20",
        endTime: "17:50",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 558,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "18:10",
        endTime: "18:40",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 559,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "19:00",
        endTime: "19:30",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 560,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "19:50",
        endTime: "20:20",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 561,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "20:40",
        endTime: "21:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 562,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "21:30",
        endTime: "22:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 575,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 576,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "11:25",
        endTime: "12:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 577,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "12:20",
        endTime: "13:05",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 578,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "13:15",
        endTime: "14:00",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 579,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "14:10",
        endTime: "14:55",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 580,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "15:05",
        endTime: "15:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 581,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 582,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "16:55",
        endTime: "17:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 583,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "17:50",
        endTime: "18:35",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 584,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "18:45",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 585,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "19:40",
        endTime: "20:25",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 586,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "20:35",
        endTime: "21:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 587,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "21:30",
        endTime: "22:15",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 601,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "9:00",
        endTime: "10:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 602,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "10:20",
        endTime: "11:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 603,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "11:40",
        endTime: "12:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 604,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "13:00",
        endTime: "14:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 605,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 606,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "16:00",
        endTime: "17:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 607,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "17:20",
        endTime: "18:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 608,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "18:40",
        endTime: "19:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 609,
        stageId: "stage-29",
        title: "ナゾラックアウト",
        artist: "さんた",
        startTime: "20:00",
        endTime: "21:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "3000",
      },
      {
        id: 630,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "8:00",
        endTime: "8:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 631,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "9:00",
        endTime: "9:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 632,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "9:55",
        endTime: "10:40",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 633,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "10:50",
        endTime: "11:35",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 634,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "12:10",
        endTime: "12:55",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 635,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "13:05",
        endTime: "13:50",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 636,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 637,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "14:55",
        endTime: "15:40",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 638,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "15:50",
        endTime: "16:35",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 639,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "16:45",
        endTime: "17:30",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 640,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "17:40",
        endTime: "18:25",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 641,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "18:50",
        endTime: "19:35",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 642,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "19:45",
        endTime: "20:30",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 643,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "20:40",
        endTime: "21:25",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 644,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "21:35",
        endTime: "22:20",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 645,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "22:30",
        endTime: "23:15",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
    ],
};
