// ★このファイルはスプレッドシート（AppScript.txt の exportToTypeScript）から自動生成される。手動編集は次回の出力で上書きされるので注意。
export default {
    title: "大阪最宴祭15 2日目 (2026/6/21)",
    startHour: 8,
    endHour: 23,
    blockMargin: 0,
    stages: [
      {
        id: "stage-1",
        name: "第1会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-2",
        name: "第2会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-3",
        name: "第3会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-4",
        name: "第4会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-5",
        name: "第5会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-7",
        name: "和室①",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-8",
        name: "和室②",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-9",
        name: "第6会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-10",
        name: "第7会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-11",
        name: "第8,9会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-12",
        name: "ステージ①",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-13",
        name: "ステージ②",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-15",
        name: "ステージ",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-16",
        name: "倉庫",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17a",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17b",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17c",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17d",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17e",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17f",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-17g",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "TRUE",
      },
      {
        id: "stage-18",
        name: "カフェ上",
        group: "レンタルスペース",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-19",
        name: "401",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-20",
        name: "403",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-21",
        name: "502",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-22",
        name: "601",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-23",
        name: "602①",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-24",
        name: "602②",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-25",
        name: "701",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-26",
        name: "702",
        group: "民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-27",
        name: "2F",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-28",
        name: "3F",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-29",
        name: "4F①",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stage-30",
        name: "4F②",
        group: "南民泊",
        allowMultiple: "",
        allowOverlap: "",
      },
    ],
    schedules: [
      {
        id: 7,
        stageId: "stage-1",
        title: "ひゃくにんと ともだちになろう",
        artist: "ナゾトキズナ",
        startTime: "11:30",
        endTime: "13:00",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 8,
        stageId: "stage-1",
        title: "ひゃくにんと ともだちになろう",
        artist: "ナゾトキズナ",
        startTime: "13:30",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 9,
        stageId: "stage-1",
        title: "ひゃくにんと ともだちになろう",
        artist: "ナゾトキズナ",
        startTime: "15:30",
        endTime: "17:00",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 10,
        stageId: "stage-1",
        title: "ひゃくにんと ともだちになろう",
        artist: "ナゾトキズナ",
        startTime: "17:30",
        endTime: "19:00",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 11,
        stageId: "stage-1",
        title: "ひゃくにんと ともだちになろう",
        artist: "ナゾトキズナ",
        startTime: "19:30",
        endTime: "21:00",
        color: "bg-red-100 border-red-300",
        fee: "2500",
      },
      {
        id: 17,
        stageId: "stage-2",
        title: "＜EX前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "10:30",
        endTime: "12:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 18,
        stageId: "stage-2",
        title: "＜通常前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "12:30",
        endTime: "14:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 19,
        stageId: "stage-2",
        title: "EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "14:30",
        endTime: "16:05",
        color: "bg-orange-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 20,
        stageId: "stage-2",
        title: "＜通常前売り切れ＞EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "16:30",
        endTime: "18:05",
        color: "bg-gray-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 21,
        stageId: "stage-2",
        title: "EmoTE STructure -エモートストラクチャー-",
        artist: "空空-karakara-",
        startTime: "18:30",
        endTime: "20:05",
        color: "bg-orange-100 border-orange-300",
        fee: "4000",
      },
      {
        id: 37,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 38,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 39,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 40,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 41,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 42,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "13:50",
        endTime: "14:20",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 43,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "15:00",
        endTime: "15:30",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 44,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "15:40",
        endTime: "16:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 45,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "16:20",
        endTime: "16:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 46,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "17:00",
        endTime: "17:30",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 47,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "17:40",
        endTime: "18:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 48,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "18:20",
        endTime: "18:50",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 49,
        stageId: "stage-3",
        title: "＜通常前売り切れ＞ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "19:00",
        endTime: "19:30",
        color: "bg-gray-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 50,
        stageId: "stage-3",
        title: "ギリギリダンシャリ",
        artist: "NAZONE",
        startTime: "19:40",
        endTime: "20:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2000",
      },
      {
        id: 57,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "10:30",
        endTime: "11:25",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 58,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "11:50",
        endTime: "12:45",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 59,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "13:10",
        endTime: "14:05",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 60,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "14:30",
        endTime: "15:25",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 61,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "15:50",
        endTime: "16:45",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 62,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "17:10",
        endTime: "18:05",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 63,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "18:30",
        endTime: "19:25",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 64,
        stageId: "stage-4",
        title: "異世界カードゲーム：ロジクス",
        artist: "おひさしぶりわーくす",
        startTime: "19:50",
        endTime: "20:45",
        color: "bg-green-100 border-green-300",
        fee: "1500",
      },
      {
        id: 69,
        stageId: "stage-5",
        title: "＜通常前売り切れ＞UNI-VERS-US",
        artist: "B [ ] X",
        startTime: "10:00",
        endTime: "12:20",
        color: "bg-gray-100 border-lime-300",
        fee: "3500",
      },
      {
        id: 70,
        stageId: "stage-5",
        title: "UNI-VERS-US",
        artist: "B [ ] X",
        startTime: "13:00",
        endTime: "15:20",
        color: "bg-lime-100 border-lime-300",
        fee: "3500",
      },
      {
        id: 71,
        stageId: "stage-5",
        title: "UNI-VERS-US",
        artist: "B [ ] X",
        startTime: "16:00",
        endTime: "18:20",
        color: "bg-lime-100 border-lime-300",
        fee: "3500",
      },
      {
        id: 78,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "10:40",
        endTime: "11:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 79,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "11:40",
        endTime: "12:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 80,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "12:40",
        endTime: "13:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 81,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 82,
        stageId: "stage-7",
        title: "＜通常前売り切れ＞〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "14:20",
        endTime: "15:00",
        color: "bg-gray-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 83,
        stageId: "stage-7",
        title: "＜通常前売り切れ＞〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "15:10",
        endTime: "15:50",
        color: "bg-gray-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 84,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "16:00",
        endTime: "16:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 85,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "16:50",
        endTime: "17:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 86,
        stageId: "stage-7",
        title: "＜通常前売り切れ＞〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "17:40",
        endTime: "18:20",
        color: "bg-gray-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 87,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 88,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "19:20",
        endTime: "20:00",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 89,
        stageId: "stage-7",
        title: "〈部屋〉は［閉ざされている］",
        artist: "作人",
        startTime: "20:10",
        endTime: "20:50",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1500",
      },
      {
        id: 90,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 91,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "11:30",
        endTime: "12:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 92,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "12:30",
        endTime: "13:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 93,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "13:30",
        endTime: "14:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 94,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "14:30",
        endTime: "15:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 95,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 96,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 97,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "17:30",
        endTime: "18:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 98,
        stageId: "stage-8",
        title: "異物混入",
        artist: "RI:Works",
        startTime: "18:30",
        endTime: "19:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 99,
        stageId: "stage-8",
        title: "＜通常前売り切れ＞異物混入",
        artist: "RI:Works",
        startTime: "19:30",
        endTime: "20:15",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 108,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 109,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "11:40",
        endTime: "12:20",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 110,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 111,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "13:20",
        endTime: "14:00",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 112,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "14:10",
        endTime: "14:50",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 113,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "15:10",
        endTime: "15:50",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 114,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "16:00",
        endTime: "16:40",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 115,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "16:50",
        endTime: "17:30",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 116,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "17:40",
        endTime: "18:20",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 117,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "18:40",
        endTime: "19:20",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 118,
        stageId: "stage-9",
        title: "＜通常前売り切れ＞Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "19:30",
        endTime: "20:10",
        color: "bg-gray-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 119,
        stageId: "stage-9",
        title: "Dさま!!６",
        artist: "Dさま!!制作委員会",
        startTime: "20:20",
        endTime: "21:00",
        color: "bg-pink-100 border-pink-300",
        fee: "2500",
      },
      {
        id: 128,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 129,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "11:45",
        endTime: "12:30",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 130,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 131,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "14:15",
        endTime: "15:00",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 132,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 133,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "16:45",
        endTime: "17:30",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 134,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 135,
        stageId: "stage-10",
        title: "潜入調査！ ぼったくり居酒屋",
        artist: "アットビ",
        startTime: "19:15",
        endTime: "20:00",
        color: "bg-blue-100 border-blue-300",
        fee: "2500",
      },
      {
        id: 140,
        stageId: "stage-11",
        title: "大逆転だ☆天使のエール",
        artist: "Tri Möbius",
        startTime: "10:30",
        endTime: "12:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "4000",
      },
      {
        id: 141,
        stageId: "stage-11",
        title: "大逆転だ☆天使のエール",
        artist: "Tri Möbius",
        startTime: "13:10",
        endTime: "14:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "4000",
      },
      {
        id: 142,
        stageId: "stage-11",
        title: "大逆転だ☆天使のエール",
        artist: "Tri Möbius",
        startTime: "15:30",
        endTime: "17:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "4000",
      },
      {
        id: 143,
        stageId: "stage-11",
        title: "大逆転だ☆天使のエール",
        artist: "Tri Möbius",
        startTime: "17:50",
        endTime: "19:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "4000",
      },
      {
        id: 154,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 155,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 156,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 157,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 158,
        stageId: "stage-12",
        title: "リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "14:50",
        endTime: "15:30",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 159,
        stageId: "stage-12",
        title: "＜通常前売り切れ＞リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "15:50",
        endTime: "16:30",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 160,
        stageId: "stage-12",
        title: "＜通常前売り切れ＞リドルヨーヨー",
        artist: "ナゾトキ番長",
        startTime: "16:50",
        endTime: "17:30",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 179,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "10:30",
        endTime: "10:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 180,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "11:00",
        endTime: "11:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 181,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "11:30",
        endTime: "11:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 182,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "12:00",
        endTime: "12:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 183,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "13:00",
        endTime: "13:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 184,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "13:30",
        endTime: "13:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 185,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "14:00",
        endTime: "14:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 186,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "14:30",
        endTime: "14:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 187,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "15:00",
        endTime: "15:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 188,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "16:00",
        endTime: "16:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 189,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "16:30",
        endTime: "16:55",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 190,
        stageId: "stage-13",
        title: "うつるんです！",
        artist: "マダミステリ屋",
        startTime: "17:00",
        endTime: "17:25",
        color: "bg-orange-100 border-orange-300",
        fee: "1000",
      },
      {
        id: 205,
        stageId: "stage-15",
        title: "HATHENA",
        artist: "HATHENA制作委員会",
        startTime: "18:30",
        endTime: "20:30",
        color: "bg-green-100 border-green-300",
        fee: "2500",
      },
      {
        id: 214,
        stageId: "stage-16",
        title: "SGO -Seiko Great Okan-",
        artist: "uranariya",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 215,
        stageId: "stage-16",
        title: "SGO -Seiko Great Okan-",
        artist: "uranariya",
        startTime: "11:20",
        endTime: "12:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 216,
        stageId: "stage-16",
        title: "SGO -Seiko Great Okan-",
        artist: "uranariya",
        startTime: "12:10",
        endTime: "12:50",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 217,
        stageId: "stage-16",
        title: "SGO -Seiko Great Okan-",
        artist: "uranariya",
        startTime: "13:50",
        endTime: "14:30",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 218,
        stageId: "stage-16",
        title: "SGO -Seiko Great Okan-",
        artist: "uranariya",
        startTime: "14:40",
        endTime: "15:20",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 229,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 230,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 231,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 232,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 233,
        stageId: "stage-17a",
        title: "＜通常前売り切れ＞公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "15:00",
        endTime: "15:50",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 234,
        stageId: "stage-17a",
        title: "＜通常前売り切れ＞公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "16:00",
        endTime: "16:50",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 235,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "17:00",
        endTime: "17:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 236,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "18:00",
        endTime: "18:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 237,
        stageId: "stage-17a",
        title: "公演版くろすにゃーど vol.1~猫の国にようこそ~",
        artist: "ラジエル-Rasiel Library-",
        startTime: "19:00",
        endTime: "19:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 251,
        stageId: "stage-17b",
        title: "パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 252,
        stageId: "stage-17b",
        title: "パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "11:40",
        endTime: "12:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 253,
        stageId: "stage-17b",
        title: "パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "12:50",
        endTime: "13:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 254,
        stageId: "stage-17b",
        title: "＜通常前売り切れ＞パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 255,
        stageId: "stage-17b",
        title: "＜通常前売り切れ＞パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 256,
        stageId: "stage-17b",
        title: "パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "16:20",
        endTime: "17:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 257,
        stageId: "stage-17b",
        title: "＜通常前売り切れ＞パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 258,
        stageId: "stage-17b",
        title: "パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 259,
        stageId: "stage-17b",
        title: "＜通常前売り切れ＞パブロフとシュレディンガー",
        artist: "CrossXOne",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 272,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 273,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "11:20",
        endTime: "12:00",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 274,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "12:10",
        endTime: "12:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 275,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "13:00",
        endTime: "13:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 276,
        stageId: "stage-17c",
        title: "＜通常前売り切れ＞ロストフィルム",
        artist: "なぞ助",
        startTime: "14:10",
        endTime: "14:50",
        color: "bg-gray-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 277,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "15:00",
        endTime: "15:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 278,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "15:50",
        endTime: "16:30",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 279,
        stageId: "stage-17c",
        title: "＜通常前売り切れ＞ロストフィルム",
        artist: "なぞ助",
        startTime: "16:40",
        endTime: "17:20",
        color: "bg-gray-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 280,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 281,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "18:20",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 282,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "19:10",
        endTime: "19:50",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 283,
        stageId: "stage-17c",
        title: "ロストフィルム",
        artist: "なぞ助",
        startTime: "20:00",
        endTime: "20:40",
        color: "bg-teal-100 border-teal-300",
        fee: "1500",
      },
      {
        id: 290,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 291,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "12:15",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 292,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "14:00",
        endTime: "15:30",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 293,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "15:45",
        endTime: "17:15",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 294,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "17:30",
        endTime: "19:00",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 295,
        stageId: "stage-17d",
        title: "RIDDLE RULE -リドルール-",
        artist: "テクニコテクニカ",
        startTime: "19:15",
        endTime: "20:45",
        color: "bg-teal-100 border-teal-300",
        fee: "4000",
      },
      {
        id: 310,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 311,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 312,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 313,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "12:35",
        endTime: "13:05",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 314,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "13:15",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 315,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "13:55",
        endTime: "14:25",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 316,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "14:40",
        endTime: "15:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 317,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "15:20",
        endTime: "15:50",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 318,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "16:00",
        endTime: "16:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 319,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "16:45",
        endTime: "17:15",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 320,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "17:25",
        endTime: "17:55",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 321,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "18:05",
        endTime: "18:35",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 322,
        stageId: "stage-17e",
        title: "＜通常前売り切れ＞ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "18:50",
        endTime: "19:20",
        color: "bg-gray-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 323,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "19:30",
        endTime: "20:00",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 324,
        stageId: "stage-17e",
        title: "ワードミュージアム3",
        artist: "ＴＫＧデラックス",
        startTime: "20:10",
        endTime: "20:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 337,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 338,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 339,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 340,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 341,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "14:30",
        endTime: "15:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 342,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 343,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 344,
        stageId: "stage-17f",
        title: "TO-KEN Phase5『Cuffs⁴』- カフス・トゥ・ザ・フォース -",
        artist: "ハテナボックス",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2500",
      },
      {
        id: 381,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "9:30",
        endTime: "10:20",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 382,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 383,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 384,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 385,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "13:30",
        endTime: "14:20",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 386,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "14:40",
        endTime: "15:30",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 387,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "15:40",
        endTime: "16:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 388,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "16:40",
        endTime: "17:30",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 389,
        stageId: "stage-18",
        title: "＜通常前売り切れ＞孤独な謎と被検体",
        artist: "algo",
        startTime: "17:40",
        endTime: "18:30",
        color: "bg-gray-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 390,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "18:50",
        endTime: "19:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 391,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 392,
        stageId: "stage-18",
        title: "孤独な謎と被検体",
        artist: "algo",
        startTime: "20:50",
        endTime: "21:40",
        color: "bg-cyan-100 border-cyan-300",
        fee: "2500",
      },
      {
        id: 403,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "10:00",
        endTime: "10:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 404,
        stageId: "stage-19",
        title: "＜通常前売り切れ＞YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 405,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 406,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 407,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 408,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "15:00",
        endTime: "15:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 409,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 410,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "17:00",
        endTime: "17:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 411,
        stageId: "stage-19",
        title: "＜通常前売り切れ＞YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "18:00",
        endTime: "18:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 412,
        stageId: "stage-19",
        title: "YOSHIDARAKE",
        artist: "CrazyLemon",
        startTime: "19:00",
        endTime: "19:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2500",
      },
      {
        id: 420,
        stageId: "stage-20",
        title: "＜通常前売り切れ＞人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "9:00",
        endTime: "10:25",
        color: "bg-gray-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 421,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "10:50",
        endTime: "12:15",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 422,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "12:40",
        endTime: "14:05",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 423,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "14:40",
        endTime: "16:05",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 424,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "16:30",
        endTime: "17:55",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 425,
        stageId: "stage-20",
        title: "人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "18:20",
        endTime: "19:45",
        color: "bg-pink-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 426,
        stageId: "stage-20",
        title: "＜通常前売り切れ＞人生一発逆転ゲームからの脱出",
        artist: "ミステリージャック",
        startTime: "20:10",
        endTime: "21:35",
        color: "bg-gray-100 border-pink-300",
        fee: "3500",
      },
      {
        id: 440,
        stageId: "stage-21",
        title: "＜通常前売り切れ＞住人と居ろ！",
        artist: "Quattrophy",
        startTime: "9:00",
        endTime: "9:45",
        color: "bg-gray-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 441,
        stageId: "stage-21",
        title: "＜通常前売り切れ＞住人と居ろ！",
        artist: "Quattrophy",
        startTime: "10:00",
        endTime: "10:45",
        color: "bg-gray-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 442,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 443,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 444,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "13:00",
        endTime: "13:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 445,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "14:00",
        endTime: "14:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 446,
        stageId: "stage-21",
        title: "＜通常前売り切れ＞住人と居ろ！",
        artist: "Quattrophy",
        startTime: "15:00",
        endTime: "15:45",
        color: "bg-gray-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 447,
        stageId: "stage-21",
        title: "住人と居ろ！",
        artist: "Quattrophy",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-blue-100 border-blue-300",
        fee: "2000",
      },
      {
        id: 459,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "9:40",
        endTime: "10:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 460,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "10:50",
        endTime: "11:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 461,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 462,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "13:10",
        endTime: "14:10",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 463,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "14:20",
        endTime: "15:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 464,
        stageId: "stage-22",
        title: "＜通常前売り切れ＞【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "15:30",
        endTime: "16:30",
        color: "bg-gray-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 465,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "16:50",
        endTime: "17:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 466,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 467,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "19:10",
        endTime: "20:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 468,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "20:20",
        endTime: "21:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 469,
        stageId: "stage-22",
        title: "【LAST STEP】なぜ成功できたのか",
        artist: "彩Riddle",
        startTime: "21:30",
        endTime: "22:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "2000",
      },
      {
        id: 480,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 481,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 482,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 483,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 484,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 485,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 486,
        stageId: "stage-23",
        title: "＜通常前売り切れ＞対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 487,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 488,
        stageId: "stage-23",
        title: "＜通常前売り切れ＞対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-gray-100 border-red-300",
        fee: "2000",
      },
      {
        id: 489,
        stageId: "stage-23",
        title: "対々和〜問い？解い！咆！〜",
        artist: "CDR",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-red-100 border-red-300",
        fee: "2000",
      },
      {
        id: 500,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 501,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 502,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 503,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 504,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 505,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 506,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 507,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 508,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 509,
        stageId: "stage-24",
        title: "ひらめきキューブワールド",
        artist: "ミステリーケーキ",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-orange-100 border-orange-300",
        fee: "2500",
      },
      {
        id: 521,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "9:30",
        endTime: "10:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 522,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 523,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 524,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 525,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "14:30",
        endTime: "15:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 526,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 527,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "16:30",
        endTime: "17:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 528,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 529,
        stageId: "stage-25",
        title: "staQube",
        artist: "あかいちゃり",
        startTime: "18:30",
        endTime: "19:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "2500",
      },
      {
        id: 540,
        stageId: "stage-26",
        title: "＜通常前売り切れ＞セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "9:40",
        endTime: "10:30",
        color: "bg-gray-100 border-green-300",
        fee: "2700",
      },
      {
        id: 541,
        stageId: "stage-26",
        title: "＜通常前売り切れ＞セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "10:40",
        endTime: "11:30",
        color: "bg-gray-100 border-green-300",
        fee: "2700",
      },
      {
        id: 542,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "11:40",
        endTime: "12:30",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 543,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "13:30",
        endTime: "14:20",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 544,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "14:30",
        endTime: "15:20",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 545,
        stageId: "stage-26",
        title: "＜通常前売り切れ＞セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-gray-100 border-green-300",
        fee: "2700",
      },
      {
        id: 546,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "16:30",
        endTime: "17:20",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 547,
        stageId: "stage-26",
        title: "セイカイ×セイセイ2",
        artist: "WHYNU",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-green-100 border-green-300",
        fee: "2700",
      },
      {
        id: 563,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "9:50",
        endTime: "10:20",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 564,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "10:40",
        endTime: "11:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 565,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "11:30",
        endTime: "12:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 566,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "12:20",
        endTime: "12:50",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 567,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 568,
        stageId: "stage-27",
        title: "＜通常前売り切れ＞Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "14:00",
        endTime: "14:30",
        color: "bg-gray-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 569,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "14:50",
        endTime: "15:20",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 570,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "15:40",
        endTime: "16:10",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 571,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "16:30",
        endTime: "17:00",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 572,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "17:20",
        endTime: "17:50",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 573,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "18:10",
        endTime: "18:40",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 574,
        stageId: "stage-27",
        title: "Protect:5 -プロテクト:ファイブ-",
        artist: "sukuranburu",
        startTime: "19:00",
        endTime: "19:30",
        color: "bg-lime-100 border-lime-300",
        fee: "1500",
      },
      {
        id: 588,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 589,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "11:25",
        endTime: "12:10",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 590,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "12:20",
        endTime: "13:05",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 591,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "13:15",
        endTime: "14:00",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 592,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "14:10",
        endTime: "14:55",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 593,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "15:05",
        endTime: "15:50",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 594,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 595,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "16:55",
        endTime: "17:40",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 596,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "17:50",
        endTime: "18:35",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 597,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "18:45",
        endTime: "19:30",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 598,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "19:40",
        endTime: "20:25",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 599,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "20:35",
        endTime: "21:20",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 600,
        stageId: "stage-28",
        title: "謎めいた部屋からの脱出２",
        artist: "トンプソン",
        startTime: "21:30",
        endTime: "22:15",
        color: "bg-teal-100 border-teal-300",
        fee: "2000",
      },
      {
        id: 610,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "9:30",
        endTime: "9:55",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 611,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "10:00",
        endTime: "10:25",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 612,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "10:30",
        endTime: "10:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 613,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "11:00",
        endTime: "11:25",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 614,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "11:30",
        endTime: "11:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 615,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "12:20",
        endTime: "12:45",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 616,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "12:50",
        endTime: "13:15",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 617,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "13:20",
        endTime: "13:45",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 618,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "13:50",
        endTime: "14:15",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 619,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "14:20",
        endTime: "14:45",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 620,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "15:30",
        endTime: "15:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 621,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "16:00",
        endTime: "16:25",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 622,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "16:30",
        endTime: "16:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 623,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "17:00",
        endTime: "17:25",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 624,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "17:30",
        endTime: "17:55",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 625,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "18:20",
        endTime: "18:45",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 626,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "18:50",
        endTime: "19:15",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 627,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "19:20",
        endTime: "19:45",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 628,
        stageId: "stage-29",
        title: "ワイワイワイプ！",
        artist: "teaparty",
        startTime: "19:50",
        endTime: "20:15",
        color: "bg-cyan-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 629,
        stageId: "stage-29",
        title: "＜通常前売り切れ＞ワイワイワイプ！",
        artist: "teaparty",
        startTime: "20:20",
        endTime: "20:45",
        color: "bg-gray-100 border-cyan-300",
        fee: "1000",
      },
      {
        id: 646,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "8:00",
        endTime: "8:45",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 647,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "8:55",
        endTime: "9:40",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 648,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "9:50",
        endTime: "10:35",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 649,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 650,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "11:55",
        endTime: "12:40",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 651,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "12:50",
        endTime: "13:35",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 652,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "13:45",
        endTime: "14:30",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 653,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "14:40",
        endTime: "15:25",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 654,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "15:35",
        endTime: "16:20",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 655,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 656,
        stageId: "stage-30",
        title: "RO-TA-TE",
        artist: "Leia",
        startTime: "17:25",
        endTime: "18:10",
        color: "bg-amber-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 657,
        stageId: "stage-30",
        title: "＜通常前売り切れ＞RO-TA-TE",
        artist: "Leia",
        startTime: "20:45",
        endTime: "21:30",
        color: "bg-gray-100 border-amber-300",
        fee: "2000",
      },
      {
        id: 691,
        stageId: "stage-17g",
        title: "＜通常前売り切れ＞Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "11:00",
        endTime: "12:00",
        color: "bg-gray-100 border-yellow-300",
        fee: "500",
      },
      {
        id: 692,
        stageId: "stage-17g",
        title: "Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "500",
      },
      {
        id: 693,
        stageId: "stage-17g",
        title: "Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "13:00",
        endTime: "14:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "500",
      },
      {
        id: 694,
        stageId: "stage-17g",
        title: "Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "14:00",
        endTime: "15:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "500",
      },
      {
        id: 695,
        stageId: "stage-17g",
        title: "Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "15:00",
        endTime: "16:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "500",
      },
      {
        id: 696,
        stageId: "stage-17g",
        title: "Gorilla? Gorilla! Gorilla!!!",
        artist: "ろぎゆき",
        startTime: "16:00",
        endTime: "17:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "500",
      },
    ],
};
