// ★このファイルはスプレッドシート（AppScript.txt の exportToTypeScript）から自動生成される。手動編集は次回の出力で上書きされるので注意。
export default {
    title: "大阪最宴祭14 2日目 (2026/2/22)",
    startHour: 9,
    endHour: 23,
    blockMargin: 0,
    stages: [
      {
        id: "room1",
        name: "第1会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room1b",
        name: "第1会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room2",
        name: "第2会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room3",
        name: "第3会議室",
        group: "浪速区民センター1F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room4",
        name: "第4会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room5",
        name: "第5会議室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "japanese",
        name: "和室",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "oasis",
        name: "休憩スペース",
        group: "浪速区民センター2F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room6",
        name: "第6会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room7",
        name: "第7会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room8",
        name: "第8会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room9",
        name: "第9会議室",
        group: "浪速区民センター3F",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "rental1",
        name: "カフェ上（大）",
        group: "レンタルスペース※階段のみ",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "rental2",
        name: "カフェ上（大）",
        group: "レンタルスペース※階段のみ",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room401",
        name: "民泊401",
        group: "民泊※エレベーターあり",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room403",
        name: "民泊403",
        group: "民泊※エレベーターあり",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room502",
        name: "民泊502",
        group: "民泊※エレベーターあり",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room602-1",
        name: "民泊602①",
        group: "民泊※エレベーターあり",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "room602-2",
        name: "民泊602②",
        group: "民泊※エレベーターあり",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stand1",
        name: "観客席",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "stand2",
        name: "観客席 他",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "booth1",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "booth2",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "booth3",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "booth4",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
      {
        id: "booth5",
        name: "ホールブース",
        group: "浪速区民センター1F ホール",
        allowMultiple: "",
        allowOverlap: "",
      },
    ],
    schedules: [
      {
        id: 1001,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1002,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "11:25",
        endTime: "12:10",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1003,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "12:20",
        endTime: "13:05",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1004,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "13:15",
        endTime: "14:00",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1005,
        stageId: "room9",
        title: "謎めいた部屋からの脱出＜通常前売り切れ＞",
        artist: "トンプソン",
        startTime: "14:10",
        endTime: "14:55",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1006,
        stageId: "room9",
        title: "謎めいた部屋からの脱出＜通常前売り切れ＞",
        artist: "トンプソン",
        startTime: "15:05",
        endTime: "15:50",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1007,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "16:00",
        endTime: "16:45",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1008,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "16:55",
        endTime: "17:40",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1009,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "17:50",
        endTime: "18:35",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 101,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 1010,
        stageId: "room9",
        title: "謎めいた部屋からの脱出",
        artist: "トンプソン",
        startTime: "18:45",
        endTime: "19:30",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 1011,
        stageId: "room9",
        title: "謎めいた部屋からの脱出＜通常前売り切れ＞",
        artist: "トンプソン",
        startTime: "19:40",
        endTime: "20:25",
        color: "bg-pink-100 border-pink-300",
        fee: "",
      },
      {
        id: 102,
        stageId: "room1",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 103,
        stageId: "room1",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 104,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 105,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 106,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "13:50",
        endTime: "14:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 107,
        stageId: "room1b",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "14:10",
        endTime: "14:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 108,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "14:30",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 109,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "14:50",
        endTime: "15:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 110,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "15:10",
        endTime: "15:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 1101,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "10:35",
        endTime: "11:45",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1102,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "13:15",
        endTime: "14:25",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1103,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "15:55",
        endTime: "17:05",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1104,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "18:35",
        endTime: "19:45",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 1105,
        stageId: "rental1",
        title: "バイオテロの脅威からの脱出",
        artist: "InTale",
        startTime: "21:15",
        endTime: "22:25",
        color: "bg-blue-100 border-blue-300",
        fee: "",
      },
      {
        id: 111,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 112,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "15:50",
        endTime: "16:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 113,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "16:10",
        endTime: "16:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 114,
        stageId: "room1",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "16:30",
        endTime: "17:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 115,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "16:50",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 116,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "17:30",
        endTime: "18:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 117,
        stageId: "room1b",
        title: "トクテン＜通常前売り切れ＞",
        artist: "WHTNU",
        startTime: "18:10",
        endTime: "18:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 118,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "18:50",
        endTime: "19:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 119,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "19:30",
        endTime: "20:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 120,
        stageId: "room1b",
        title: "トクテン",
        artist: "WHTNU",
        startTime: "20:10",
        endTime: "20:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 1201,
        stageId: "rental2",
        title: "Escape from the Game in Game＜通常前売り切れ＞",
        artist: "InTale",
        startTime: "9:20",
        endTime: "10:20",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1202,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1203,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "14:40",
        endTime: "15:40",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1204,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "17:20",
        endTime: "18:20",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1205,
        stageId: "rental2",
        title: "Escape from the Game in Game",
        artist: "InTale",
        startTime: "20:00",
        endTime: "21:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1301,
        stageId: "room401",
        title: "OPEN EXIT＜通常前売り切れ＞",
        artist: "Leia",
        startTime: "9:00",
        endTime: "9:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1302,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "10:00",
        endTime: "10:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1303,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "11:00",
        endTime: "11:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1304,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "12:00",
        endTime: "12:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1305,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "14:20",
        endTime: "15:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1306,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "15:20",
        endTime: "16:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1307,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "16:20",
        endTime: "17:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1308,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "17:20",
        endTime: "18:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1309,
        stageId: "room401",
        title: "OPEN EXIT＜通常前売り切れ＞",
        artist: "Leia",
        startTime: "18:20",
        endTime: "19:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1310,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "20:00",
        endTime: "20:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1311,
        stageId: "room401",
        title: "OPEN EXIT＜通常前売り切れ＞",
        artist: "Leia",
        startTime: "21:00",
        endTime: "21:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1312,
        stageId: "room401",
        title: "OPEN EXIT",
        artist: "Leia",
        startTime: "22:00",
        endTime: "22:40",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1401,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1402,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "11:45",
        endTime: "12:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1403,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "13:15",
        endTime: "14:15",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1404,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "14:30",
        endTime: "15:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1405,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "15:45",
        endTime: "16:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1406,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "17:00",
        endTime: "18:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1407,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "18:30",
        endTime: "19:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1408,
        stageId: "room403",
        title: "リドルステークス",
        artist: "すぎやまいっぺい",
        startTime: "19:45",
        endTime: "20:45",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1501,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ＜通常前売り切れ＞",
        artist: "Flambeur’s Coin",
        startTime: "10:00",
        endTime: "10:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1502,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1503,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "11:55",
        endTime: "12:40",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1504,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "13:15",
        endTime: "14:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1505,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "14:10",
        endTime: "14:55",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1506,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ＜通常前売り切れ＞",
        artist: "Flambeur’s Coin",
        startTime: "15:05",
        endTime: "15:50",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1507,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "16:15",
        endTime: "17:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1508,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "17:10",
        endTime: "17:55",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1509,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ",
        artist: "Flambeur’s Coin",
        startTime: "18:05",
        endTime: "18:50",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1510,
        stageId: "room502",
        title: "フラフラ　フラっとフラコイナゾ＜通常前売り切れ＞",
        artist: "Flambeur’s Coin",
        startTime: "19:00",
        endTime: "19:45",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 1601,
        stageId: "room602-1",
        title: "収集癖＜通常前売り切れ＞",
        artist: "CDR",
        startTime: "9:20",
        endTime: "10:05",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1602,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "10:30",
        endTime: "11:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1603,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "11:30",
        endTime: "12:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1604,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "12:30",
        endTime: "13:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1605,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "13:30",
        endTime: "14:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1606,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "15:30",
        endTime: "16:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1607,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "16:30",
        endTime: "17:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1608,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "17:30",
        endTime: "18:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1609,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "18:30",
        endTime: "19:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1610,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "19:30",
        endTime: "20:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1611,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "20:30",
        endTime: "21:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1612,
        stageId: "room602-1",
        title: "収集癖",
        artist: "CDR",
        startTime: "21:30",
        endTime: "22:15",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 1701,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？＜通常前売り切れ＞",
        artist: "ミステリーケーキ",
        startTime: "9:20",
        endTime: "10:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1702,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1703,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1704,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1705,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "13:30",
        endTime: "14:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1706,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1707,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1708,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1709,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1710,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "19:30",
        endTime: "20:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1711,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？＜通常前売り切れ＞",
        artist: "ミステリーケーキ",
        startTime: "20:30",
        endTime: "21:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1712,
        stageId: "room602-2",
        title: "ダジャレを解くのは誰じゃ！？",
        artist: "ミステリーケーキ",
        startTime: "21:30",
        endTime: "22:10",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 1801,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "10:30",
        endTime: "10:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1802,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "10:50",
        endTime: "11:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1803,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "11:10",
        endTime: "11:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1804,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "11:30",
        endTime: "11:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1805,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "11:50",
        endTime: "12:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1806,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "12:10",
        endTime: "12:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1807,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "12:30",
        endTime: "12:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1808,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "12:50",
        endTime: "13:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1809,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "13:10",
        endTime: "13:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1810,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "13:30",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1811,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "13:50",
        endTime: "14:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1812,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "14:10",
        endTime: "14:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1813,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "14:30",
        endTime: "14:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1814,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "14:50",
        endTime: "15:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1815,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "15:10",
        endTime: "15:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1816,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "15:30",
        endTime: "15:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1817,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "15:50",
        endTime: "16:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1818,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "16:10",
        endTime: "16:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1819,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "16:30",
        endTime: "16:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1820,
        stageId: "stand1",
        title: "階段落ちからの脱出＜通常前売り切れ＞",
        artist: "シングルズ",
        startTime: "16:50",
        endTime: "17:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1821,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "17:10",
        endTime: "17:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1822,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "17:30",
        endTime: "17:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1823,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "17:50",
        endTime: "18:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1824,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "18:10",
        endTime: "18:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1825,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "18:30",
        endTime: "18:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1826,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "18:50",
        endTime: "19:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1827,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "19:10",
        endTime: "19:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1828,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "19:30",
        endTime: "19:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1829,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "19:50",
        endTime: "20:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1830,
        stageId: "stand1",
        title: "階段落ちからの脱出",
        artist: "シングルズ",
        startTime: "20:10",
        endTime: "20:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 1901,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "10:30",
        endTime: "12:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1902,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "12:00",
        endTime: "13:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1903,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "13:30",
        endTime: "15:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1904,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "15:00",
        endTime: "16:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1905,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "16:30",
        endTime: "18:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1906,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "18:00",
        endTime: "19:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 1907,
        stageId: "stand2",
        title: "Letter to You/＄HOW & BU￥",
        artist: "なぞすぽっと",
        startTime: "19:30",
        endTime: "21:00",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 2001,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "10:30",
        endTime: "11:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2002,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "11:30",
        endTime: "12:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2003,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "12:30",
        endTime: "13:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2004,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "14:30",
        endTime: "15:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2005,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "15:30",
        endTime: "16:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2006,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "16:30",
        endTime: "17:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2007,
        stageId: "booth4",
        title: "ハッタリハッタリ＜通常前売り切れ＞",
        artist: "ComeCozy",
        startTime: "17:30",
        endTime: "18:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2008,
        stageId: "booth4",
        title: "ハッタリハッタリ＜Ex前売り切れ＞",
        artist: "ComeCozy",
        startTime: "18:30",
        endTime: "19:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 201,
        stageId: "room2",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 202,
        stageId: "room2",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "11:40",
        endTime: "12:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 203,
        stageId: "room2",
        title: "Q■の■分リドルクッキング＜通常前売り切れ＞",
        artist: "Ereka",
        startTime: "12:50",
        endTime: "13:40",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 204,
        stageId: "room2",
        title: "Q■の■分リドルクッキング＜通常前売り切れ＞",
        artist: "Ereka",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 205,
        stageId: "room2",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 206,
        stageId: "room2",
        title: "Q■の■分リドルクッキング＜通常前売り切れ＞",
        artist: "Ereka",
        startTime: "16:20",
        endTime: "17:10",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 207,
        stageId: "room2",
        title: "Q■の■分リドルクッキング＜通常前売り切れ＞",
        artist: "Ereka",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 208,
        stageId: "room2",
        title: "Q■の■分リドルクッキング＜通常前売り切れ＞",
        artist: "Ereka",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 209,
        stageId: "room2",
        title: "Q■の■分リドルクッキング",
        artist: "Ereka",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-orange-100 border-orange-300",
        fee: "",
      },
      {
        id: 2101,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "10:30",
        endTime: "10:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2102,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "10:55",
        endTime: "11:15",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2103,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜通常前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "11:20",
        endTime: "11:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2104,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "11:45",
        endTime: "12:05",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2105,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜通常前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "12:10",
        endTime: "12:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2106,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:00",
        endTime: "13:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2107,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:25",
        endTime: "13:45",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2108,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "13:50",
        endTime: "14:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2109,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "14:15",
        endTime: "14:35",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2110,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜通常前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "14:40",
        endTime: "15:00",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2111,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:30",
        endTime: "15:50",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2112,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "15:55",
        endTime: "16:15",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2113,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "16:20",
        endTime: "16:40",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2114,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "16:45",
        endTime: "17:05",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2115,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜通常前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "17:10",
        endTime: "17:30",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2116,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜通常前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "18:00",
        endTime: "18:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2117,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:25",
        endTime: "18:45",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2118,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "18:50",
        endTime: "19:10",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2119,
        stageId: "booth5",
        title: "まっきー1本 謎のもと＜Ex前売り切れ＞",
        artist: "すぎやまっきー",
        startTime: "19:15",
        endTime: "19:35",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2120,
        stageId: "booth5",
        title: "まっきー1本 謎のもと",
        artist: "すぎやまっきー",
        startTime: "19:40",
        endTime: "20:00",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2201,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2202,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2203,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2204,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "13:30",
        endTime: "14:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2205,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "14:30",
        endTime: "15:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2206,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2207,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "16:30",
        endTime: "17:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2208,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2209,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "18:30",
        endTime: "19:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2210,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "19:30",
        endTime: "20:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2211,
        stageId: "oasis",
        title: "爆処TEQ Case.1 Rulic Cube",
        artist: "テクニコテクニカ",
        startTime: "20:30",
        endTime: "21:20",
        color: "bg-indigo-100 border-indigo-300",
        fee: "",
      },
      {
        id: 2301,
        stageId: "booth1",
        title: "イロハコネクト＜通常前売り切れ＞",
        artist: "J's C Labo",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2302,
        stageId: "booth1",
        title: "イロハコネクト",
        artist: "J's C Labo",
        startTime: "12:00",
        endTime: "13:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2303,
        stageId: "booth1",
        title: "イロハコネクト",
        artist: "J's C Labo",
        startTime: "13:30",
        endTime: "14:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2304,
        stageId: "booth1",
        title: "イロハコネクト＜通常前売り切れ＞",
        artist: "J's C Labo",
        startTime: "15:00",
        endTime: "16:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2305,
        stageId: "booth1",
        title: "イロハコネクト",
        artist: "J's C Labo",
        startTime: "16:30",
        endTime: "17:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2306,
        stageId: "booth1",
        title: "イロハコネクト",
        artist: "J's C Labo",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2307,
        stageId: "booth1",
        title: "イロハコネクト",
        artist: "J's C Labo",
        startTime: "19:30",
        endTime: "20:30",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 2401,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス",
        artist: "CrossXOne",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2402,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス",
        artist: "CrossXOne",
        startTime: "11:40",
        endTime: "12:30",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2403,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス",
        artist: "CrossXOne",
        startTime: "12:50",
        endTime: "13:40",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2404,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス",
        artist: "CrossXOne",
        startTime: "14:00",
        endTime: "14:50",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2405,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス＜通常前売り切れ＞",
        artist: "CrossXOne",
        startTime: "15:10",
        endTime: "16:00",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2406,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス＜通常前売り切れ＞",
        artist: "CrossXOne",
        startTime: "16:20",
        endTime: "17:10",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2407,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス＜通常前売り切れ＞",
        artist: "CrossXOne",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2408,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス",
        artist: "CrossXOne",
        startTime: "18:40",
        endTime: "19:30",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2409,
        stageId: "booth2",
        title: "笑うディーラーとポーカーフェイス＜通常前売り切れ＞",
        artist: "CrossXOne",
        startTime: "19:50",
        endTime: "20:40",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 2501,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2502,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2503,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2504,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "12:35",
        endTime: "13:05",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2505,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "13:15",
        endTime: "13:45",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2506,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "13:55",
        endTime: "14:25",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2507,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "14:40",
        endTime: "15:10",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2508,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "15:20",
        endTime: "15:50",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2509,
        stageId: "booth3",
        title: "ワードミュージアム2＜通常前売り切れ＞",
        artist: "TKGデラックス",
        startTime: "16:00",
        endTime: "16:30",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2510,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "16:45",
        endTime: "17:15",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2511,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "17:25",
        endTime: "17:55",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2512,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "18:05",
        endTime: "18:35",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2513,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "18:50",
        endTime: "19:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2514,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "19:30",
        endTime: "20:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 2515,
        stageId: "booth3",
        title: "ワードミュージアム2",
        artist: "TKGデラックス",
        startTime: "20:10",
        endTime: "20:40",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 301,
        stageId: "room3",
        title: "韻すぴれーしょん",
        artist: "CrazyLemon",
        startTime: "10:30",
        endTime: "11:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 302,
        stageId: "room3",
        title: "韻すぴれーしょん＜通常前売り切れ＞",
        artist: "CrazyLemon",
        startTime: "11:30",
        endTime: "12:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 303,
        stageId: "room3",
        title: "韻すぴれーしょん＜通常前売り切れ＞",
        artist: "CrazyLemon",
        startTime: "12:30",
        endTime: "13:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 304,
        stageId: "room3",
        title: "韻すぴれーしょん",
        artist: "CrazyLemon",
        startTime: "13:30",
        endTime: "14:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 305,
        stageId: "room3",
        title: "韻すぴれーしょん",
        artist: "CrazyLemon",
        startTime: "14:30",
        endTime: "15:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 306,
        stageId: "room3",
        title: "韻すぴれーしょん",
        artist: "CrazyLemon",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 307,
        stageId: "room3",
        title: "韻すぴれーしょん＜通常前売り切れ＞",
        artist: "CrazyLemon",
        startTime: "16:30",
        endTime: "17:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 308,
        stageId: "room3",
        title: "韻すぴれーしょん＜通常前売り切れ＞",
        artist: "CrazyLemon",
        startTime: "17:30",
        endTime: "18:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 309,
        stageId: "room3",
        title: "韻すぴれーしょん＜通常前売り切れ＞",
        artist: "CrazyLemon",
        startTime: "18:30",
        endTime: "19:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 310,
        stageId: "room3",
        title: "韻すぴれーしょん",
        artist: "CrazyLemon",
        startTime: "19:30",
        endTime: "20:20",
        color: "bg-yellow-100 border-yellow-300",
        fee: "",
      },
      {
        id: 401,
        stageId: "room4",
        title: "I WANNA BE FREE",
        artist: "Mの会",
        startTime: "11:00",
        endTime: "12:30",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 402,
        stageId: "room4",
        title: "I WANNA BE FREE",
        artist: "Mの会",
        startTime: "13:30",
        endTime: "15:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 403,
        stageId: "room4",
        title: "I WANNA BE FREE",
        artist: "Mの会",
        startTime: "16:00",
        endTime: "17:30",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 404,
        stageId: "room4",
        title: "I WANNA BE FREE",
        artist: "Mの会",
        startTime: "18:30",
        endTime: "20:00",
        color: "bg-green-100 border-green-300",
        fee: "",
      },
      {
        id: 501,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "11:00",
        endTime: "12:05",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 502,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "12:30",
        endTime: "13:35",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 503,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "14:00",
        endTime: "15:05",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 504,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "15:30",
        endTime: "16:35",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 505,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "17:00",
        endTime: "18:05",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 506,
        stageId: "room5",
        title: "不完全な脱出ゲームからの脱出",
        artist: "Qlock",
        startTime: "18:30",
        endTime: "19:35",
        color: "bg-lime-100 border-lime-300",
        fee: "",
      },
      {
        id: 601,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "10:30",
        endTime: "11:40",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 602,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "11:50",
        endTime: "13:00",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 603,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "13:10",
        endTime: "14:20",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 604,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "15:00",
        endTime: "16:10",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 605,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "16:20",
        endTime: "17:30",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 606,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "17:40",
        endTime: "18:50",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 607,
        stageId: "japanese",
        title: "面白いみんなの謎解き",
        artist: "やずろぼばこ",
        startTime: "19:00",
        endTime: "20:10",
        color: "bg-teal-100 border-teal-300",
        fee: "",
      },
      {
        id: 701,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "10:30",
        endTime: "12:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 702,
        stageId: "room6",
        title: "EmoTE STructure＜通常前売り切れ＞",
        artist: "空空-karakara-",
        startTime: "12:30",
        endTime: "14:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 703,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "14:30",
        endTime: "16:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 704,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "16:30",
        endTime: "18:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 705,
        stageId: "room6",
        title: "EmoTE STructure",
        artist: "空空-karakara-",
        startTime: "18:30",
        endTime: "20:05",
        color: "bg-cyan-100 border-cyan-300",
        fee: "",
      },
      {
        id: 801,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 802,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "11:40",
        endTime: "12:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 803,
        stageId: "room7",
        title: "The BOX＜通常前売り切れ＞",
        artist: "Melt",
        startTime: "12:50",
        endTime: "13:50",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 804,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "14:00",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 805,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "15:10",
        endTime: "16:10",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 806,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "16:20",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 807,
        stageId: "room7",
        title: "The BOX＜通常前売り切れ＞",
        artist: "Melt",
        startTime: "17:30",
        endTime: "18:30",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 808,
        stageId: "room7",
        title: "The BOX",
        artist: "Melt",
        startTime: "18:40",
        endTime: "19:40",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 809,
        stageId: "room7",
        title: "The BOX＜通常前売り切れ＞",
        artist: "Melt",
        startTime: "19:50",
        endTime: "20:50",
        color: "bg-red-100 border-red-300",
        fee: "",
      },
      {
        id: 901,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "10:30",
        endTime: "11:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 902,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "11:50",
        endTime: "12:50",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 903,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "13:10",
        endTime: "14:10",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 904,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "14:30",
        endTime: "15:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 905,
        stageId: "room8",
        title: "フィッシュボーンアンサー",
        artist: "X LixiT",
        startTime: "15:50",
        endTime: "16:50",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 906,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "17:10",
        endTime: "18:10",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
      {
        id: 907,
        stageId: "room8",
        title: "フィッシュボーンアンサー＜通常前売り切れ＞",
        artist: "X LixiT",
        startTime: "18:30",
        endTime: "19:30",
        color: "bg-amber-100 border-amber-300",
        fee: "",
      },
    ],
};
