export const EVENTS_DB = {
  "saienfes14-day1": {
    title: "大阪最宴祭14 1日目 (2026/2/21)",
    startHour: 9,
    endHour: 23,
    stages: [
      {
        id: "room1",
        name: "第1会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room1b",
        name: "第1会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room2",
        name: "第2会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room3",
        name: "第3会議室",
        group: "浪速区民センター1F",
      },
      {
        id: "room4",
        name: "第4会議室",
        group: "浪速区民センター2F",
      },
      {
        id: "room5",
        name: "第5会議室",
        group: "浪速区民センター2F",
      },
      {
        id: "japanese",
        name: "和室",
        group: "浪速区民センター2F",
      },
      {
        id: "room6",
        name: "第6会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room7",
        name: "第7会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room8",
        name: "第8会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "room9",
        name: "第9会議室",
        group: "浪速区民センター3F",
      },
      {
        id: "hall",
        name: "カフェ上（大）",
        group: "レンタルスペース※階段のみ",
      },
      {
        id: "room401",
        name: "民泊401",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room403",
        name: "民泊403",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room502",
        name: "民泊502",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room602-1",
        name: "民泊602①",
        group: "民泊※エレベーターあり",
      },
      {
        id: "room602-2",
        name: "民泊602②",
        group: "民泊※エレベーターあり",
      },
      {
        id: "stage1",
        name: "ステージ①",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "stand",
        name: "観客席",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "booth1",
        name: "ホールブース①",
        group: "浪速区民センター1F ホール",
      },
      {
        id: "booth2",
        name: "ホールブース②",
        group: "浪速区民センター1F ホール",
      },
    ],
    schedules: [
      {
        id: 101,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "10:30",
        endTime: "11:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 102,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "11:10",
        endTime: "11:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 103,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "11:50",
        endTime: "12:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 104,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "12:30",
        endTime: "13:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 105,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "13:10",
        endTime: "13:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 106,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "13:50",
        endTime: "14:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 107,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:10",
        endTime: "14:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 108,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:30",
        endTime: "15:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 109,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "14:50",
        endTime: "15:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 110,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:10",
        endTime: "15:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 111,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 112,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "15:50",
        endTime: "16:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 113,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:10",
        endTime: "16:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 114,
        stageId: "room1",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:30",
        endTime: "17:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 115,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "16:50",
        endTime: "17:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 116,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "17:30",
        endTime: "18:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 117,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "18:10",
        endTime: "18:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 118,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "18:50",
        endTime: "19:20",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 119,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "19:30",
        endTime: "20:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 120,
        stageId: "room1b",
        title: "トクチン",
        artist: "WHTNU",
        startTime: "20:10",
        endTime: "20:40",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 200,
        stageId: "room2",
        title: "も",
        artist: "TKGデラックス",
        startTime: "10:00",
        endTime: "11:00",
        color: "bg-orange-100 border-orange-300",
      },
      {
        id: 201,
        stageId: "room3",
        title: "Aniatus",
        artist: "ハテナボックス",
        startTime: "10:00",
        endTime: "11:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 202,
        stageId: "room4",
        title: "Jack's Party",
        artist: "ミステリージャック",
        startTime: "10:00",
        endTime: "11:00",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 203,
        stageId: "room8",
        title: "Escape from the Game in Game",
        artist: "ShareKODE",
        startTime: "10:00",
        endTime: "11:10",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 204,
        stageId: "room9",
        title: "PLUS MINUS",
        artist: "ナゾトキズナ",
        startTime: "10:00",
        endTime: "11:00",
        color: "bg-indigo-100 border-indigo-300",
      },
      {
        id: 205,
        stageId: "cafe401",
        title: "リドルステークス",
        artist: "Lata",
        startTime: "12:30",
        endTime: "13:30",
        color: "bg-purple-100 border-purple-300",
      },
      {
        id: 206,
        stageId: "room502",
        title: "THE LOST CARD",
        artist: "Flambeur's Coby",
        startTime: "12:30",
        endTime: "13:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 207,
        stageId: "room602",
        title: "Letters to You",
        artist: "COR",
        startTime: "12:30",
        endTime: "13:30",
        color: "bg-rose-100 border-rose-300",
      },
      {
        id: 208,
        stageId: "hall",
        title: "ハッタリハッテ",
        artist: "ComeCozy",
        startTime: "13:00",
        endTime: "14:00",
        color: "bg-gray-100 border-gray-300",
      },
      {
        id: 209,
        stageId: "room6",
        title: "EmuTE Structure",
        artist: "シングルス",
        startTime: "13:00",
        endTime: "14:00",
        color: "bg-teal-100 border-teal-300",
      },
      {
        id: 210,
        stageId: "room5",
        title: "マスターから...",
        artist: "スパイシードロップス",
        startTime: "15:30",
        endTime: "16:20",
        color: "bg-lime-100 border-lime-300",
      },
      {
        id: 211,
        stageId: "room7",
        title: "The BOX",
        artist: "Karakuri",
        startTime: "15:30",
        endTime: "16:30",
        color: "bg-cyan-100 border-cyan-300",
      },
      {
        id: 212,
        stageId: "room1",
        title: "トクチン (夜公演)",
        artist: "WHTNU",
        startTime: "18:00",
        endTime: "19:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 213,
        stageId: "room8",
        title: "Escape from the Game in Game (夜公演)",
        artist: "ShareKODE",
        startTime: "18:00",
        endTime: "19:10",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 214,
        stageId: "room403",
        title: "??? (公演内容確認中)",
        artist: "すまやよいつい",
        startTime: "19:00",
        endTime: "20:00",
        color: "bg-amber-100 border-amber-300",
      },
      {
        id: 215,
        stageId: "main",
        title: "オープニングセレモニー",
        artist: "実行委員会",
        startTime: "10:00",
        endTime: "10:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 216,
        stageId: "gym",
        title: "吹奏楽部演奏",
        artist: "吹奏楽部",
        startTime: "10:15",
        endTime: "11:00",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 217,
        stageId: "main",
        title: "お笑いライブ",
        artist: "ゲスト芸人",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 218,
        stageId: "outdoor",
        title: "バンド演奏 A",
        artist: "軽音部A",
        startTime: "11:00",
        endTime: "11:30",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 219,
        stageId: "classroom",
        title: "アコースティックライブ",
        artist: "弾き語り同好会",
        startTime: "11:15",
        endTime: "12:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 220,
        stageId: "main",
        title: "ダンスパフォーマンス",
        artist: "ダンス部",
        startTime: "12:15",
        endTime: "13:00",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 221,
        stageId: "outdoor",
        title: "サイエンスショー",
        artist: "科学部",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 222,
        stageId: "gym",
        title: "演劇「ロミオとジュリエット」",
        artist: "演劇部",
        startTime: "13:00",
        endTime: "14:30",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 223,
        stageId: "main",
        title: "Mr. & Ms. コンテスト",
        artist: "ファイナリスト",
        startTime: "13:30",
        endTime: "14:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 224,
        stageId: "classroom",
        title: "ジャズセッション",
        artist: "ジャズ研",
        startTime: "14:00",
        endTime: "15:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 225,
        stageId: "outdoor",
        title: "バンド演奏 B",
        artist: "軽音部B",
        startTime: "14:45",
        endTime: "15:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 226,
        stageId: "main",
        title: "グランドフィナーレ",
        artist: "全員集合",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 227,
        stageId: "red",
        title: "Headliner Live",
        artist: "Super Star",
        startTime: "18:00",
        endTime: "20:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 228,
        stageId: "blue",
        title: "DJ Night",
        artist: "DJ Taro",
        startTime: "18:00",
        endTime: "21:00",
        color: "bg-blue-100 border-blue-300",
      },
    ],
  },
  "saienfes14-day2": {
    title: "大阪最宴祭14 2日目 (2026/2/22)",
    startHour: 9,
    endHour: 23,
    stages: [],
    schedules: [],
  },
  "saienfes14-day3": {
    title: "大阪最宴祭14 3日目 (2026/2/23)",
    startHour: 9,
    endHour: 23,
    stages: [],
    schedules: [],
  },
};
