export const EVENTS_DB = {
  saienfes14: {
    title: "Saienfes 14",
    stages: [
      { id: "main", name: "メインステージ" },
      { id: "gym", name: "体育館ステージ" },
      { id: "outdoor", name: "野外ステージ" },
      { id: "classroom", name: "教室ライブ" },
      { id: "main2", name: "メインステージ" },
      { id: "gym2", name: "体育館ステージ" },
      { id: "outdoor2", name: "野外ステージ" },
      { id: "classroom2", name: "教室ライブ" },
      { id: "main3", name: "メインステージ" },
      { id: "gym3", name: "体育館ステージ" },
      { id: "outdoor3", name: "野外ステージ" },
      { id: "classroom3", name: "教室ライブ" },
    ],
    schedules: [
      {
        id: 1,
        stageId: "main",
        title: "オープニングセレモニー",
        artist: "実行委員会",
        startTime: "10:00",
        endTime: "10:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 2,
        stageId: "gym",
        title: "吹奏楽部演奏",
        artist: "吹奏楽部",
        startTime: "10:15",
        endTime: "11:00",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 3,
        stageId: "main",
        title: "お笑いライブ",
        artist: "ゲスト芸人",
        startTime: "11:00",
        endTime: "11:45",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 4,
        stageId: "outdoor",
        title: "バンド演奏 A",
        artist: "軽音部A",
        startTime: "11:00",
        endTime: "11:30",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 5,
        stageId: "classroom",
        title: "アコースティックライブ",
        artist: "弾き語り同好会",
        startTime: "11:15",
        endTime: "12:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 6,
        stageId: "main",
        title: "ダンスパフォーマンス",
        artist: "ダンス部",
        startTime: "12:15",
        endTime: "13:00",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 7,
        stageId: "outdoor",
        title: "サイエンスショー",
        artist: "科学部",
        startTime: "12:00",
        endTime: "12:45",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 8,
        stageId: "gym",
        title: "演劇「ロミオとジュリエット」",
        artist: "演劇部",
        startTime: "13:00",
        endTime: "14:30",
        color: "bg-blue-100 border-blue-300",
      },
      {
        id: 9,
        stageId: "main",
        title: "Mr. & Ms. コンテスト",
        artist: "ファイナリスト",
        startTime: "13:30",
        endTime: "14:30",
        color: "bg-pink-100 border-pink-300",
      },
      {
        id: 10,
        stageId: "classroom",
        title: "ジャズセッション",
        artist: "ジャズ研",
        startTime: "14:00",
        endTime: "15:00",
        color: "bg-yellow-100 border-yellow-300",
      },
      {
        id: 11,
        stageId: "outdoor",
        title: "バンド演奏 B",
        artist: "軽音部B",
        startTime: "14:45",
        endTime: "15:15",
        color: "bg-green-100 border-green-300",
      },
      {
        id: 12,
        stageId: "main",
        title: "グランドフィナーレ",
        artist: "全員集合",
        startTime: "15:30",
        endTime: "16:00",
        color: "bg-pink-100 border-pink-300",
      },
    ],
  },
  "summer-fes-demo": {
    title: "Summer Festival Demo",
    stages: [
      { id: "red", name: "RED STAGE" },
      { id: "blue", name: "BLUE STAGE" },
    ],
    schedules: [
      {
        id: 101,
        stageId: "red",
        title: "Headliner Live",
        artist: "Super Star",
        startTime: "18:00",
        endTime: "20:00",
        color: "bg-red-100 border-red-300",
      },
      {
        id: 102,
        stageId: "blue",
        title: "DJ Night",
        artist: "DJ Taro",
        startTime: "18:00",
        endTime: "21:00",
        color: "bg-blue-100 border-blue-300",
      },
    ],
  },
};
